// CodeGear C++Builder
// Copyright (c) 1995, 2015 by Embarcadero Technologies, Inc.
// All rights reserved

// (DO NOT EDIT: machine generated header) 'wclUUIDs.pas' rev: 30.00 (Windows)

#ifndef WcluuidsHPP
#define WcluuidsHPP

#pragma delphiheader begin
#pragma option push
#pragma option -w-      // All warnings off
#pragma option -Vx      // Zero-length empty class member 
#pragma pack(push,8)
#include <System.hpp>
#include <SysInit.hpp>

//-- user supplied -----------------------------------------------------------

namespace Wcluuids
{
//-- forward type declarations -----------------------------------------------
//-- type declarations -------------------------------------------------------
//-- var, const, procedure ---------------------------------------------------
extern DELPHI_PACKAGE GUID Bluetooth_Base_UUID;
extern DELPHI_PACKAGE GUID SDP_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID UDP_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID RFCOMM_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID TCP_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID TCSBIN_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID TCSAT_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID ATT_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID OBEX_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID IP_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID FTP_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID HTTP_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID WSP_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID BNEP_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID UPNP_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID HID_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID HCCC_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID HCDC_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID HN_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID AVCTP_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID AVDTP_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID CMPT_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID UDI_C_PLANE_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID MCAP_CONTROL_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID MCAP_DATA_PROTOCOL_UUID;
extern DELPHI_PACKAGE GUID L2CAP_PROTOCOL_UUID;
static const System::Int8 SDP_PROTOCOL_UUID16 = System::Int8(0x1);
static const System::Int8 UDP_PROTOCOL_UUID16 = System::Int8(0x2);
static const System::Int8 RFCOMM_PROTOCOL_UUID16 = System::Int8(0x3);
static const System::Int8 TCP_PROTOCOL_UUID16 = System::Int8(0x4);
static const System::Int8 TCSBIN_PROTOCOL_UUID16 = System::Int8(0x5);
static const System::Int8 TCSAT_PROTOCOL_UUID16 = System::Int8(0x6);
static const System::Int8 ATT_PROTOCOL_UUID16 = System::Int8(0x7);
static const System::Int8 OBEX_PROTOCOL_UUID16 = System::Int8(0x8);
static const System::Int8 IP_PROTOCOL_UUID16 = System::Int8(0x9);
static const System::Int8 FTP_PROTOCOL_UUID16 = System::Int8(0xa);
static const System::Int8 HTTP_PROTOCOL_UUID16 = System::Int8(0xc);
static const System::Int8 WSP_PROTOCOL_UUID16 = System::Int8(0xe);
static const System::Int8 BNEP_PROTOCOL_UUID16 = System::Int8(0xf);
static const System::Int8 UPNP_PROTOCOL_UUID16 = System::Int8(0x10);
static const System::Int8 HID_PROTOCOL_UUID16 = System::Int8(0x11);
static const System::Int8 HCCC_PROTOCOL_UUID16 = System::Int8(0x12);
static const System::Int8 HCDC_PROTOCOL_UUID16 = System::Int8(0x14);
static const System::Int8 HN_PROTOCOL_UUID16 = System::Int8(0x16);
static const System::Int8 AVCTP_PROTOCOL_UUID16 = System::Int8(0x17);
static const System::Int8 AVDTP_PROTOCOL_UUID16 = System::Int8(0x19);
static const System::Int8 CMPT_PROTOCOL_UUID16 = System::Int8(0x1b);
static const System::Int8 UDI_C_PLANE_PROTOCOL_UUID16 = System::Int8(0x1d);
static const System::Int8 MCAP_CONTROL_PROTOCOL_UUID16 = System::Int8(0x1e);
static const System::Int8 MCAP_DATA_PROTOCOL_UUID16 = System::Int8(0x1f);
static const System::Word L2CAP_PROTOCOL_UUID16 = System::Word(0x100);
extern DELPHI_PACKAGE GUID ServiceDiscoveryServerServiceClassID_UUID;
extern DELPHI_PACKAGE GUID BrowseGroupDescriptorServiceClassID_UUID;
extern DELPHI_PACKAGE GUID PublicBrowseGroupServiceClass_UUID;
extern DELPHI_PACKAGE GUID SerialPortServiceClass_UUID;
extern DELPHI_PACKAGE GUID LANAccessUsingPPPServiceClass_UUID;
extern DELPHI_PACKAGE GUID DialupNetworkingServiceClass_UUID;
extern DELPHI_PACKAGE GUID IrMCSyncServiceClass_UUID;
extern DELPHI_PACKAGE GUID OBEXObjectPushServiceClass_UUID;
extern DELPHI_PACKAGE GUID OBEXFileTransferServiceClass_UUID;
extern DELPHI_PACKAGE GUID IrMCSyncCommandServiceClass_UUID;
extern DELPHI_PACKAGE GUID HeadsetServiceClass_UUID;
extern DELPHI_PACKAGE GUID CordlessTelephonyServiceClass_UUID;
extern DELPHI_PACKAGE GUID AudioSourceServiceClass_UUID;
extern DELPHI_PACKAGE GUID AudioSinkServiceClass_UUID;
extern DELPHI_PACKAGE GUID AVRemoteControlTargetServiceClass_UUID;
extern DELPHI_PACKAGE GUID AdvancedAudioDistributionServiceClass_UUID;
extern DELPHI_PACKAGE GUID AVRemoteControlServiceClass_UUID;
extern DELPHI_PACKAGE GUID VideoConferencingServiceClass_UUID;
extern DELPHI_PACKAGE GUID IntercomServiceClass_UUID;
extern DELPHI_PACKAGE GUID FaxServiceClass_UUID;
extern DELPHI_PACKAGE GUID HeadsetAudioGatewayServiceClass_UUID;
extern DELPHI_PACKAGE GUID WAPServiceClass_UUID;
extern DELPHI_PACKAGE GUID WAPClientServiceClass_UUID;
extern DELPHI_PACKAGE GUID PANUServiceClass_UUID;
extern DELPHI_PACKAGE GUID NAPServiceClass_UUID;
extern DELPHI_PACKAGE GUID GNServiceClass_UUID;
extern DELPHI_PACKAGE GUID DirectPrintingServiceClass_UUID;
extern DELPHI_PACKAGE GUID ReferencePrintingServiceClass_UUID;
extern DELPHI_PACKAGE GUID ImagingServiceClass_UUID;
extern DELPHI_PACKAGE GUID ImagingResponderServiceClass_UUID;
extern DELPHI_PACKAGE GUID ImagingAutomaticArchiveServiceClass_UUID;
extern DELPHI_PACKAGE GUID ImagingReferenceObjectsServiceClass_UUID;
extern DELPHI_PACKAGE GUID HandsfreeServiceClass_UUID;
extern DELPHI_PACKAGE GUID HandsfreeAudioGatewayServiceClass_UUID;
extern DELPHI_PACKAGE GUID DirectPrintingReferenceObjectsServiceClass_UUID;
extern DELPHI_PACKAGE GUID ReflectedUIServiceClass_UUID;
extern DELPHI_PACKAGE GUID BasicPrintingServiceClass_UUID;
extern DELPHI_PACKAGE GUID PrintingStatusServiceClass_UUID;
extern DELPHI_PACKAGE GUID HumanInterfaceDeviceServiceClass_UUID;
extern DELPHI_PACKAGE GUID HardcopyCableReplacementServiceClass_UUID;
extern DELPHI_PACKAGE GUID HCRPrintServiceClass_UUID;
extern DELPHI_PACKAGE GUID HCRScanServiceClass_UUID;
extern DELPHI_PACKAGE GUID CommonISDNAccessServiceClass_UUID;
extern DELPHI_PACKAGE GUID VideoConferencingGWServiceClass_UUID;
extern DELPHI_PACKAGE GUID UDIMTServiceClass_UUID;
extern DELPHI_PACKAGE GUID UDITAServiceClass_UUID;
extern DELPHI_PACKAGE GUID AudioVideoServiceClass_UUID;
extern DELPHI_PACKAGE GUID SimAccessServiceClass_UUID;
extern DELPHI_PACKAGE GUID PhonebookClientEquipmentServiceClass_UUID;
extern DELPHI_PACKAGE GUID PhonebookServerEquipmentServiceClass_UUID;
extern DELPHI_PACKAGE GUID PhonebookServiceClass_UUID;
extern DELPHI_PACKAGE GUID HeadsetHSServiceClass_UUID;
extern DELPHI_PACKAGE GUID MessageAccessServerServiceClass_UUID;
extern DELPHI_PACKAGE GUID MessageNotificationServerServiceClass_UUID;
extern DELPHI_PACKAGE GUID MessageAccessProfileServiceClass_UUID;
extern DELPHI_PACKAGE GUID GNSSProfileServiceClass_UUID;
extern DELPHI_PACKAGE GUID GNSSServerServiceClass_UUID;
extern DELPHI_PACKAGE GUID ThreeDDisplayServiceClass_UUID;
extern DELPHI_PACKAGE GUID ThreeDGlassesServiceClass_UUID;
extern DELPHI_PACKAGE GUID ThreeDSynchronizationProfileServiceClass_UUID;
extern DELPHI_PACKAGE GUID MPSProfileServiceClass_UUID;
extern DELPHI_PACKAGE GUID MPSSCServiceClass_UUID;
extern DELPHI_PACKAGE GUID CTNAccessServiceClass_UUID;
extern DELPHI_PACKAGE GUID CTNNotificationServiceClass_UUID;
extern DELPHI_PACKAGE GUID CTNProfileServiceClass_UUID;
extern DELPHI_PACKAGE GUID PnPInformationServiceClass_UUID;
extern DELPHI_PACKAGE GUID GenericNetworkingServiceClass_UUID;
extern DELPHI_PACKAGE GUID GenericFileTransferServiceClass_UUID;
extern DELPHI_PACKAGE GUID GenericAudioServiceClass_UUID;
extern DELPHI_PACKAGE GUID GenericTelephonyServiceClass_UUID;
extern DELPHI_PACKAGE GUID UPnpServiceClass_UUID;
extern DELPHI_PACKAGE GUID UPnpIpServiceClass_UUID;
extern DELPHI_PACKAGE GUID ESdpUpnpIpPanServiceClass_UUID;
extern DELPHI_PACKAGE GUID ESdpUpnpIpLapServiceClass_UUID;
extern DELPHI_PACKAGE GUID ESdpUpnpL2capServiceClass_UUID;
extern DELPHI_PACKAGE GUID VideoSourceServiceClass_UUID;
extern DELPHI_PACKAGE GUID VideoSinkServiceClass_UUID;
extern DELPHI_PACKAGE GUID VideoDistributionServiceClass_UUID;
extern DELPHI_PACKAGE GUID HDPServiceClass_UUID;
extern DELPHI_PACKAGE GUID HDPSourceServiceClass_UUID;
extern DELPHI_PACKAGE GUID HDPSinkServiceClass_UUID;
extern DELPHI_PACKAGE GUID SyncMLServerServiceClass_UUID;
extern DELPHI_PACKAGE GUID SyncMLClientServiceClass_UUID;
extern DELPHI_PACKAGE GUID NokiaOBEXPCSuiteServiceClass_UUID;
static const System::Word ServiceDiscoveryServerServiceClassID_UUID16 = System::Word(0x1000);
static const System::Word BrowseGroupDescriptorServiceClassID_UUID16 = System::Word(0x1001);
static const System::Word PublicBrowseGroupServiceClass_UUID16 = System::Word(0x1002);
static const System::Word SerialPortServiceClass_UUID16 = System::Word(0x1101);
static const System::Word LANAccessUsingPPPServiceClass_UUID16 = System::Word(0x1102);
static const System::Word DialupNetworkingServiceClass_UUID16 = System::Word(0x1103);
static const System::Word IrMCSyncServiceClass_UUID16 = System::Word(0x1104);
static const System::Word OBEXObjectPushServiceClass_UUID16 = System::Word(0x1105);
static const System::Word OBEXFileTransferServiceClass_UUID16 = System::Word(0x1106);
static const System::Word IrMCSyncCommandServiceClass_UUID16 = System::Word(0x1107);
static const System::Word HeadsetServiceClass_UUID16 = System::Word(0x1108);
static const System::Word CordlessTelephonyServiceClass_UUID16 = System::Word(0x1109);
static const System::Word AudioSourceServiceClass_UUID16 = System::Word(0x110a);
static const System::Word AudioSinkServiceClass_UUID16 = System::Word(0x110b);
static const System::Word AVRemoteControlTargetServiceClass_UUID16 = System::Word(0x110c);
static const System::Word AdvancedAudioDistributionServiceClass_UUID16 = System::Word(0x110d);
static const System::Word AVRemoteControlServiceClass_UUID16 = System::Word(0x110e);
static const System::Word VideoConferencingServiceClass_UUID16 = System::Word(0x110f);
static const System::Word IntercomServiceClass_UUID16 = System::Word(0x1110);
static const System::Word FaxServiceClass_UUID16 = System::Word(0x1111);
static const System::Word HeadsetAudioGatewayServiceClass_UUID16 = System::Word(0x1112);
static const System::Word WAPServiceClass_UUID16 = System::Word(0x1113);
static const System::Word WAPClientServiceClass_UUID16 = System::Word(0x1114);
static const System::Word PANUServiceClass_UUID16 = System::Word(0x1115);
static const System::Word NAPServiceClass_UUID16 = System::Word(0x1116);
static const System::Word GNServiceClass_UUID16 = System::Word(0x1117);
static const System::Word DirectPrintingServiceClass_UUID16 = System::Word(0x1118);
static const System::Word ReferencePrintingServiceClass_UUID16 = System::Word(0x1119);
static const System::Word ImagingServiceClass_UUID16 = System::Word(0x111a);
static const System::Word ImagingResponderServiceClass_UUID16 = System::Word(0x111b);
static const System::Word ImagingAutomaticArchiveServiceClass_UUID16 = System::Word(0x111c);
static const System::Word ImagingReferenceObjectsServiceClass_UUID16 = System::Word(0x111d);
static const System::Word HandsfreeServiceClass_UUID16 = System::Word(0x111e);
static const System::Word HandsfreeAudioGatewayServiceClass_UUID16 = System::Word(0x111f);
static const System::Word DirectPrintingReferenceObjectsServiceClass_UUID16 = System::Word(0x1120);
static const System::Word ReflectedUIServiceClass_UUID16 = System::Word(0x1121);
static const System::Word BasicPrintingServiceClass_UUID16 = System::Word(0x1122);
static const System::Word PrintingStatusServiceClass_UUID16 = System::Word(0x1123);
static const System::Word HumanInterfaceDeviceServiceClass_UUID16 = System::Word(0x1124);
static const System::Word HardcopyCableReplacementServiceClass_UUID16 = System::Word(0x1125);
static const System::Word HCRPrintServiceClass_UUID16 = System::Word(0x1126);
static const System::Word HCRScanServiceClass_UUID16 = System::Word(0x1127);
static const System::Word CommonISDNAccessServiceClass_UUID16 = System::Word(0x1128);
static const System::Word VideoConferencingGWServiceClass_UUID16 = System::Word(0x1129);
static const System::Word UDIMTServiceClass_UUID16 = System::Word(0x112a);
static const System::Word UDITAServiceClass_UUID16 = System::Word(0x112b);
static const System::Word AudioVideoServiceClass_UUID16 = System::Word(0x112c);
static const System::Word SimAccessServiceClass_UUID16 = System::Word(0x112d);
static const System::Word PhonebookClientEquipmentServiceClass_UUID16 = System::Word(0x112e);
static const System::Word PhonebookServerEquipmentServiceClass_UUID16 = System::Word(0x112f);
static const System::Word PhonebookServiceClass_UUID16 = System::Word(0x1130);
static const System::Word HeadsetHSServiceClass_UUID16 = System::Word(0x1131);
static const System::Word MessageAccessServerServiceClass_UUID16 = System::Word(0x1132);
static const System::Word MessageNotificationServerServiceClass_UUID16 = System::Word(0x1133);
static const System::Word MessageAccessProfileServiceClass_UUID16 = System::Word(0x1134);
static const System::Word GNSSProfileServiceClass_UUID16 = System::Word(0x1135);
static const System::Word GNSSServerServiceClass_UUID16 = System::Word(0x1136);
static const System::Word ThreeDDisplayServiceClass_UUID16 = System::Word(0x1137);
static const System::Word ThreeDGlassesServiceClass_UUID16 = System::Word(0x1138);
static const System::Word ThreeDSynchronizationProfileServiceClass_UUID16 = System::Word(0x1139);
static const System::Word MPSProfileServiceClass_UUID16 = System::Word(0x113a);
static const System::Word MPSSCServiceClass_UUID16 = System::Word(0x113b);
static const System::Word CTNAccessServiceClass_UUID16 = System::Word(0x113c);
static const System::Word CTNNotificationServiceClass_UUID16 = System::Word(0x113d);
static const System::Word CTNProfileServiceClass_UUID16 = System::Word(0x113e);
static const System::Word PnPInformationServiceClass_UUID16 = System::Word(0x1200);
static const System::Word GenericNetworkingServiceClass_UUID16 = System::Word(0x1201);
static const System::Word GenericFileTransferServiceClass_UUID16 = System::Word(0x1202);
static const System::Word GenericAudioServiceClass_UUID16 = System::Word(0x1203);
static const System::Word GenericTelephonyServiceClass_UUID16 = System::Word(0x1204);
static const System::Word UPnpServiceClass_UUID16 = System::Word(0x1205);
static const System::Word UPnpIpServiceClass_UUID16 = System::Word(0x1206);
static const System::Word ESdpUpnpIpPanServiceClass_UUID16 = System::Word(0x1300);
static const System::Word ESdpUpnpIpLapServiceClass_UUID16 = System::Word(0x1301);
static const System::Word ESdpUpnpL2capServiceClass_UUID16 = System::Word(0x1302);
static const System::Word VideoSourceServiceClass_UUID16 = System::Word(0x1303);
static const System::Word VideoSinkServiceClass_UUID16 = System::Word(0x1304);
static const System::Word VideoDistributionServiceClass_UUID16 = System::Word(0x1305);
static const System::Word HDPServiceClass_UUID16 = System::Word(0x1400);
static const System::Word HDPSourceServiceClass_UUID16 = System::Word(0x1401);
static const System::Word HDPSinkServiceClass_UUID16 = System::Word(0x1402);
static const System::Int8 PSM_SDP = System::Int8(0x1);
static const System::Int8 PSM_RFCOMM = System::Int8(0x3);
static const System::Int8 PSM_TCS_BIN = System::Int8(0x5);
static const System::Int8 PSM_TCS_BIN_CORDLESS = System::Int8(0x7);
static const System::Int8 PSM_BNEP = System::Int8(0xf);
static const System::Int8 PSM_HID_CONTROL = System::Int8(0x11);
static const System::Int8 PSM_HID_INTERRUPT = System::Int8(0x13);
static const System::Int8 PSM_UPNP = System::Int8(0x15);
static const System::Int8 PSM_AVCTP = System::Int8(0x17);
static const System::Int8 PSM_AVDTP = System::Int8(0x19);
static const System::Int8 PSM_AVCTP_BROWSE = System::Int8(0x1b);
static const System::Int8 PSM_UDI_C_PLANE = System::Int8(0x1d);
static const System::Int8 PSM_ATT = System::Int8(0x1f);
static const System::Int8 PSM_3DSP = System::Int8(0x21);
static const System::Int8 PSM_LE_IPSP = System::Int8(0x23);
static const System::Int8 PSM_OTS = System::Int8(0x25);
static const System::Int8 PSM_EATT = System::Int8(0x27);
extern DELPHI_PACKAGE GUID LE_ATT_BLUETOOTH_BASE_GUID;
static const System::Word GATT_SERVICE_GAP = System::Word(0x1800);
static const System::Word GATT_SERVICE_GATT = System::Word(0x1801);
static const System::Word GATT_SERVICE_IMMEDIATE_ALERT = System::Word(0x1802);
static const System::Word GATT_SERVICE_LINK_LOSS = System::Word(0x1803);
static const System::Word GATT_SERVICE_TX_POWER = System::Word(0x1804);
static const System::Word GATT_SERVICE_CURRENT_TIME = System::Word(0x1805);
static const System::Word GATT_SERVICE_REFERENCE_TIME_UPDATE = System::Word(0x1806);
static const System::Word GATT_SERVICE_NEXT_SDT_CHANGE = System::Word(0x1807);
static const System::Word GATT_SERVICE_GLUCOSE = System::Word(0x1808);
static const System::Word GATT_SERVICE_HEALTH_THERMOMETER = System::Word(0x1809);
static const System::Word GATT_SERVICE_DEVICE_INFORMATION = System::Word(0x180a);
static const System::Word GATT_SERVICE_HEART_RATE = System::Word(0x180d);
static const System::Word GATT_SERVICE_PHONE_ALERT_STATUS = System::Word(0x180e);
static const System::Word GATT_SERVICE_BATTERY = System::Word(0x180f);
static const System::Word GATT_SERVICE_BLOOD_PRESSURE = System::Word(0x1810);
static const System::Word GATT_SERVICE_ALERT_NOTIFICATION = System::Word(0x1811);
static const System::Word GATT_SERVICE_HID = System::Word(0x1812);
static const System::Word GATT_SERVICE_SCAN_PARAMETERS = System::Word(0x1813);
static const System::Word GATT_SERVICE_RUNNING_SPEED_AND_CADENCE = System::Word(0x1814);
static const System::Word GATT_SERVICE_AUTOMATION_IO = System::Word(0x1815);
static const System::Word GATT_SERVICE_CYCLING_SPEED_AND_CADENCE = System::Word(0x1816);
static const System::Word GATT_SERVICE_CYCLING_POWER = System::Word(0x1818);
static const System::Word GATT_SERVICE_LOCATION_AND_NAVIGATION = System::Word(0x1819);
static const System::Word GATT_SERVICE_ENVIRONMENTAL_SENSING = System::Word(0x181a);
static const System::Word GATT_SERVICE_BODY_COMPOSITION = System::Word(0x181b);
static const System::Word GATT_SERVICE_USER_DATA = System::Word(0x181c);
static const System::Word GATT_SERVICE_WEIGHT_SCALE = System::Word(0x181d);
static const System::Word GATT_SERVICE_BOND_MANAGEMENT = System::Word(0x181e);
static const System::Word GATT_SERVICE_CONTINUOUS_GLUCOSE_MONITORING = System::Word(0x181f);
static const System::Word GATT_SERVICE_INTERNET_PROTOCOL_SUPPORT = System::Word(0x1820);
static const System::Word GATT_SERVICE_INDOOR_POSITIONING = System::Word(0x1821);
static const System::Word GATT_SERVICE_PULSE_OXIMETER = System::Word(0x1822);
static const System::Word GATT_SERVICE_HTTP_PROXY = System::Word(0x1823);
static const System::Word GATT_SERVICE_TRANSPORT_DISCOVERY = System::Word(0x1824);
static const System::Word GATT_SERVICE_OBJECT_TRANSFER = System::Word(0x1825);
static const System::Word GATT_SERVICE_FITNESS_MACHINE = System::Word(0x1826);
static const System::Word GATT_SERVICE_MESH_PROVISIONING = System::Word(0x1827);
static const System::Word GATT_SERVICE_MESH_PROXY = System::Word(0x1828);
static const System::Word GATT_SERVICE_RECONNECTION_CONFIGURATION = System::Word(0x1829);
static const System::Word GATT_SERVICE_INSULIN_DELIVERY = System::Word(0x183a);
static const System::Word GATT_SERVICE_BINARY_SENSOR = System::Word(0x183b);
static const System::Word GATT_SERVICE_EMERGENCY_CONFIGURATION = System::Word(0x183c);
static const System::Word GATT_SERVICE_AUTHORIZATION_CONTROL = System::Word(0x183d);
static const System::Word GATT_SERVICE_PHYSICAL_ACTIVITY_MONITOR = System::Word(0x183e);
static const System::Word GATT_SERVICE_ELAPSED_TIME = System::Word(0x183f);
static const System::Word GATT_SERVICE_GENERIC_HEALTH_SENSOR = System::Word(0x1840);
static const System::Word GATT_SERVICE_AUDIO_INPUT_CONTROL = System::Word(0x1843);
static const System::Word GATT_SERVICE_VOLUME_CONTROL = System::Word(0x1844);
static const System::Word GATT_SERVICE_VOLUME_OFFSET_CONTROL = System::Word(0x1845);
static const System::Word GATT_SERVICE_COORDINATED_SET_IDENTIFICATION = System::Word(0x1846);
static const System::Word GATT_SERVICE_DEVICE_TIME = System::Word(0x1847);
static const System::Word GATT_SERVICE_MEDIA_CONTROL = System::Word(0x1848);
static const System::Word GATT_SERVICE_GENERIC_MEDIA_CONTROL = System::Word(0x1849);
static const System::Word GATT_SERVICE_CONSTANT_TONE_EXTENSION = System::Word(0x184a);
static const System::Word GATT_SERVICE_TELEPHONE_BEARER = System::Word(0x184b);
static const System::Word GATT_SERVICE_GENERIC_TELEPHONE_BEARER = System::Word(0x184c);
static const System::Word GATT_SERVICE_MICROPHONE_CONTROL = System::Word(0x184d);
static const System::Word GATT_SERVICE_AUDIO_STREAM_CONTROL = System::Word(0x184e);
static const System::Word GATT_SERVICE_BROADCAST_AUDIO_SCAN = System::Word(0x184f);
static const System::Word GATT_SERVICE_PUBLISHED_AUDIO_CAPABILITIES = System::Word(0x1850);
static const System::Word GATT_SERVICE_BASIC_AUDIO_ANNOUNCEMENT = System::Word(0x1851);
static const System::Word GATT_SERVICE_BROADCAST_AUDIO_ANNOUNCEMENT = System::Word(0x1852);
static const System::Word GATT_SERVICE_COMMON_AUDIO = System::Word(0x1853);
static const System::Word GATT_SERVICE_HEARING_ACCESS = System::Word(0x1854);
static const System::Word GATT_SERVICE_TELEPHONY_AND_MEDIA_AUDIO = System::Word(0x1855);
static const System::Word GATT_SERVICE_PUBLIC_BROADCAST_ANNOUNCEMENT = System::Word(0x1856);
static const System::Word GATT_SERVICE_ELECTRONIC_SHELF_LABEL = System::Word(0x1857);
static const System::Word GATT_SERVICE_GAMING_AUDIO = System::Word(0x1858);
static const System::Word GATT_SERVICE_MESH_PROXY_SOLICITATION = System::Word(0x1859);
static const System::Word GATT_ATTRIBUTE_TYPE_PRIMARY_SERVICE = System::Word(0x2800);
static const System::Word GATT_ATTRIBUTE_TYPE_SECONDARY_SERVICE = System::Word(0x2801);
static const System::Word GATT_ATTRIBUTE_TYPE_INCLUDE = System::Word(0x2802);
static const System::Word GATT_ATTRIBUTE_TYPE_CHARACTERISTIC = System::Word(0x2803);
static const System::Word GATT_DESCRIPTOR_CHARACTERISTIC_EXTENDED_PROPERTIES = System::Word(0x2900);
static const System::Word GATT_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION = System::Word(0x2901);
static const System::Word GATT_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION = System::Word(0x2902);
static const System::Word GATT_DESCRIPTOR_SERVER_CHARACTERISTIC_CONFIGURATION = System::Word(0x2903);
static const System::Word GATT_DESCRIPTOR_CHARACTERISTIC_PRESENTATION_FORMAT = System::Word(0x2904);
static const System::Word GATT_DESCRIPTOR_CHARACTERISTIC_AGGREGATE_FORMAT = System::Word(0x2905);
static const System::Word GATT_DESCRIPTOR_VALID_RANGE = System::Word(0x2906);
static const System::Word GATT_DESCRIPTOR_EXTERNAL_REPORT_REFERENCE = System::Word(0x2907);
static const System::Word GATT_DESCRIPTOR_REPORT_REFERENCE = System::Word(0x2908);
static const System::Word GATT_DESCRIPTOR_NUMBER_OF_DIGITALS = System::Word(0x2909);
static const System::Word GATT_DESCRIPTOR_VALUE_TRIGGER_SETTING = System::Word(0x290a);
static const System::Word GATT_DESCRIPTOR_ENVIRONMENTAL_SENSING_CONFIGURATION = System::Word(0x290b);
static const System::Word GATT_DESCRIPTOR_ENVIRONMENTAL_SENSING_MEASUREMENT = System::Word(0x290c);
static const System::Word GATT_DESCRIPTOR_ENVIRONMENTAL_SENSING_TRIGGER_SETTING = System::Word(0x290d);
static const System::Word GATT_DESCRIPTOR_TIME_TRIGGER_SETTING = System::Word(0x290e);
static const System::Word GATT_DESCRIPTOR_COLPLETE_BR_EDR_TRANSPORT_BLOCK_DATA = System::Word(0x290f);
static const System::Word GATT_DESCRIPTOR_OBSERVATION_SCHEDULE = System::Word(0x2910);
static const System::Word GATT_DESCRIPTOR_VALID_RANGE_AND_ACCURACY = System::Word(0x2911);
static const System::Word GATT_CHARACTERISTIC_DEVICE_NAME = System::Word(0x2a00);
static const System::Word GATT_CHARACTERISTIC_APPEARANCE = System::Word(0x2a01);
static const System::Word GATT_CHARACTERISTIC_PERIPHERAL_PRIVACY_FLAG = System::Word(0x2a02);
static const System::Word GATT_CHARACTERISTIC_RECONNECTION_ADDRESS = System::Word(0x2a03);
static const System::Word GATT_CHARACTERISTIC_PERIPHERAL_PREFERRED_CONNECTION_PARAMETERS = System::Word(0x2a04);
static const System::Word GATT_CHARACTERISTIC_SERVICE_CHANGED = System::Word(0x2a05);
static const System::Word GATT_CHARACTERISTIC_ALERT_LEVEL = System::Word(0x2a06);
static const System::Word GATT_CHARACTERISTIC_TX_POWER_LEVEL = System::Word(0x2a07);
static const System::Word GATT_CHARACTERISTIC_DATE_TIME = System::Word(0x2a08);
static const System::Word GATT_CHARACTERISTIC_DAY_OF_WEEK = System::Word(0x2a09);
static const System::Word GATT_CHARACTERISTIC_DAY_DATE_TIME = System::Word(0x2a0a);
static const System::Word GATT_CHARACTERISTIC_EXACT_TIME_256 = System::Word(0x2a0c);
static const System::Word GATT_CHARACTERISTIC_DST_OFFSET = System::Word(0x2a0d);
static const System::Word GATT_CHARACTERISTIC_TIME_ZONE = System::Word(0x2a0e);
static const System::Word GATT_CHARACTERISTIC_LOCAL_TIME_INFORMATION = System::Word(0x2a0f);
static const System::Word GATT_CHARACTERISTIC_TIME_WITH_DST = System::Word(0x2a11);
static const System::Word GATT_CHARACTERISTIC_TIME_ACCURACY = System::Word(0x2a12);
static const System::Word GATT_CHARACTERISTIC_TIME_SOURCE = System::Word(0x2a13);
static const System::Word GATT_CHARACTERISTIC_REFERENCE_TIME_INFORMATION = System::Word(0x2a14);
static const System::Word GATT_CHARACTERISTIC_TIME_UPDATE_CONTROL_POINT = System::Word(0x2a16);
static const System::Word GATT_CHARACTERISTIC_TIME_UPDATE_STATE = System::Word(0x2a17);
static const System::Word GATT_CHARACTERISTIC_GLUCOSE_MEASUREMENT = System::Word(0x2a18);
static const System::Word GATT_CHARACTERISTIC_BATTERY_LEVEL = System::Word(0x2a19);
static const System::Word GATT_CHARACTERISTIC_TEMPERATURE_MEASUREMENT = System::Word(0x2a1c);
static const System::Word GATT_CHARACTERISTIC_TEMPERATURE_TYPE = System::Word(0x2a1d);
static const System::Word GATT_CHARACTERISTIC_INTERMEDIATE_TEMPERATURE = System::Word(0x2a1e);
static const System::Word GATT_CHARACTERISTIC_MEASUREMENT_INTERVAL = System::Word(0x2a21);
static const System::Word GATT_CHARACTERISTIC_BOOT_KEYBOARD_INPUT_REPORT = System::Word(0x2a22);
static const System::Word GATT_CHARACTERISTIC_SYSTEM_ID = System::Word(0x2a23);
static const System::Word GATT_CHARACTERISTIC_MODEL_NUMBER_STRING = System::Word(0x2a24);
static const System::Word GATT_CHARACTERISTIC_SERIAL_NUMBER_STRING = System::Word(0x2a25);
static const System::Word GATT_CHARACTERISTIC_FIRMWARE_REVISION_STRING = System::Word(0x2a26);
static const System::Word GATT_CHARACTERISTIC_HARDWARE_REVISION_STRING = System::Word(0x2a27);
static const System::Word GATT_CHARACTERISTIC_SOFTWARE_REVISION_STRING = System::Word(0x2a28);
static const System::Word GATT_CHARACTERISTIC_MANUFACTURER_NAME_STRING = System::Word(0x2a29);
static const System::Word GATT_CHARACTERISTIC_IEEE_CERTIFICATION_DATA_LIST = System::Word(0x2a2a);
static const System::Word GATT_CHARACTERISTIC_CURRENT_TIME = System::Word(0x2a2b);
static const System::Word GATT_CHARACTERISTIC_MAGNETIC_DECLINATION = System::Word(0x2a2c);
static const System::Word GATT_CHARACTERISTIC_SCAN_REFRESH = System::Word(0x2a31);
static const System::Word GATT_CHARACTERISTIC_BOOT_KEYBOARD_OUTPUT_REPORT = System::Word(0x2a32);
static const System::Word GATT_CHARACTERISTIC_BOOT_MOUSE_INPUT_REPORT = System::Word(0x2a33);
static const System::Word GATT_CHARACTERISTIC_GLUCOSE_MEASUREMENT_CONTEXT = System::Word(0x2a34);
static const System::Word GATT_CHARACTERISTIC_BLOOD_PRESSURE_MEASUREMENT = System::Word(0x2a35);
static const System::Word GATT_CHARACTERISTIC_INTERMEDIATE_CUFF_PRESSURE = System::Word(0x2a36);
static const System::Word GATT_CHARACTERISTIC_HEART_RATE_MEASUREMENT = System::Word(0x2a37);
static const System::Word GATT_CHARACTERISTIC_BODY_SENSOR_LOCATION = System::Word(0x2a38);
static const System::Word GATT_CHARACTERISTIC_HEART_RATE_CONTROL_POINT = System::Word(0x2a39);
static const System::Word GATT_CHARACTERISTIC_ALERT_STATUS = System::Word(0x2a3f);
static const System::Word GATT_CHARACTERISTIC_RINGER_CONTROL_POINT = System::Word(0x2a40);
static const System::Word GATT_CHARACTERISTIC_RINGER_SETTING = System::Word(0x2a41);
static const System::Word GATT_CHARACTERISTIC_ALERT_CATEGORY_ID_BIT_MASK = System::Word(0x2a42);
static const System::Word GATT_CHARACTERISTIC_ALERT_CATEGORY_ID = System::Word(0x2a43);
static const System::Word GATT_CHARACTERISTIC_ALERT_NOTIFICATION_CONTROL_POINT = System::Word(0x2a44);
static const System::Word GATT_CHARACTERISTIC_UNREAD_ALERT_STATUS = System::Word(0x2a45);
static const System::Word GATT_CHARACTERISTIC_NEW_ALERT = System::Word(0x2a46);
static const System::Word GATT_CHARACTERISTIC_SUPPORTED_NEW_ALERT_CATEGORY = System::Word(0x2a47);
static const System::Word GATT_CHARACTERISTIC_SUPPORTED_UNREAD_ALERT_CATEGORY = System::Word(0x2a48);
static const System::Word GATT_CHARACTERISTIC_BLOOD_PRESSURE_FEATURE = System::Word(0x2a49);
static const System::Word GATT_CHARACTERISTIC_HID_INFORMATION = System::Word(0x2a4a);
static const System::Word GATT_CHARACTERISTIC_REPORT_MAP = System::Word(0x2a4b);
static const System::Word GATT_CHARACTERISTIC_HID_CONTROL_POINT = System::Word(0x2a4c);
static const System::Word GATT_CHARACTERISTIC_REPORT = System::Word(0x2a4d);
static const System::Word GATT_CHARACTERISTIC_PROTOCOL_MODE = System::Word(0x2a4e);
static const System::Word GATT_CHARACTERISTIC_SCAN_INTERVAL_WINDOW = System::Word(0x2a4f);
static const System::Word GATT_CHARACTERISTIC_PNP_ID = System::Word(0x2a50);
static const System::Word GATT_CHARACTERISTIC_GLUCOSE_FEATURE = System::Word(0x2a51);
static const System::Word GATT_CHARACTERISTIC_RECORD_ACCESS_CONTROL_POINT = System::Word(0x2a52);
static const System::Word GATT_CHARACTERISTIC_RSC_MEASUREMENT = System::Word(0x2a53);
static const System::Word GATT_CHARACTERISTIC_RSC_FEATURE = System::Word(0x2a54);
static const System::Word GATT_CHARACTERISTIC_SC_CONTROL_POINT = System::Word(0x2a55);
static const System::Word GATT_CHARACTERISTIC_AGGREGATE = System::Word(0x2a5a);
static const System::Word GATT_CHARACTERISTIC_CSC_MEASUREMENT = System::Word(0x2a5b);
static const System::Word GATT_CHARACTERISTIC_CSC_FEATURE = System::Word(0x2a5c);
static const System::Word GATT_CHARACTERISTIC_SENSOR_LOCATION = System::Word(0x2a5d);
static const System::Word GATT_CHARACTERISTIC_PLX_SPOT_CHECK_MEASUREMENT = System::Word(0x2a5e);
static const System::Word GATT_CHARACTERISTIC_PLX_CONTINUOUS_MEASUREMENT = System::Word(0x2a5f);
static const System::Word GATT_CHARACTERISTIC_PLX_FEATURES = System::Word(0x2a60);
static const System::Word GATT_CHARACTERISTIC_CYCLING_POWER_MEASUREMENT = System::Word(0x2a63);
static const System::Word GATT_CHARACTERISTIC_CYCLING_POWER_VECTOR = System::Word(0x2a64);
static const System::Word GATT_CHARACTERISTIC_CYCLING_POWER_FEATURE = System::Word(0x2a65);
static const System::Word GATT_CHARACTERISTIC_CYCLING_POWER_CONTROL_POINT = System::Word(0x2a66);
static const System::Word GATT_CHARACTERISTIC_LOCATION_AND_SPEED = System::Word(0x2a67);
static const System::Word GATT_CHARACTERISTIC_NAVIGATION = System::Word(0x2a68);
static const System::Word GATT_CHARACTERISTIC_POSITION_QUALITY = System::Word(0x2a69);
static const System::Word GATT_CHARACTERISTIC_LN_FEATURE = System::Word(0x2a6a);
static const System::Word GATT_CHARACTERISTIC_LN_CONTROL_POINT = System::Word(0x2a6b);
static const System::Word GATT_CHARACTERISTIC_ELEVATION = System::Word(0x2a6c);
static const System::Word GATT_CHARACTERISTIC_PRESSURE = System::Word(0x2a6d);
static const System::Word GATT_CHARACTERISTIC_TEMPERATURE = System::Word(0x2a6e);
static const System::Word GATT_CHARACTERISTIC_HUMIDITY = System::Word(0x2a6f);
static const System::Word GATT_CHARACTERISTIC_TRUE_WIND_SPEED = System::Word(0x2a70);
static const System::Word GATT_CHARACTERISTIC_TRUE_WIND_DIRECTION = System::Word(0x2a71);
static const System::Word GATT_CHARACTERISTIC_APPARENT_WIND_SPEED = System::Word(0x2a72);
static const System::Word GATT_CHARACTERISTIC_APPARENT_WIND_DIRECTION = System::Word(0x2a73);
static const System::Word GATT_CHARACTERISTIC_GUST_FACTOR = System::Word(0x2a74);
static const System::Word GATT_CHARACTERISTIC_POLLEN_CONCENTRATION = System::Word(0x2a75);
static const System::Word GATT_CHARACTERISTIC_UV_INDEX = System::Word(0x2a76);
static const System::Word GATT_CHARACTERISTIC_IRRADIANCE = System::Word(0x2a77);
static const System::Word GATT_CHARACTERISTIC_RAINFALL = System::Word(0x2a78);
static const System::Word GATT_CHARACTERISTIC_WIND_CHILL = System::Word(0x2a79);
static const System::Word GATT_CHARACTERISTIC_HEAT_INDEX = System::Word(0x2a7a);
static const System::Word GATT_CHARACTERISTIC_DEW_POINT = System::Word(0x2a7b);
static const System::Word GATT_CHARACTERISTIC_DESCRIPTOR_VALUE_CHANGED = System::Word(0x2a7d);
static const System::Word GATT_CHARACTERISTIC_AEROBIC_HEART_RATE_LOWER_LIMIT = System::Word(0x2a7e);
static const System::Word GATT_CHARACTERISTIC_AEROBIC_TRESHOLD = System::Word(0x2a7f);
static const System::Word GATT_CHARACTERISTIC_AGE = System::Word(0x2a80);
static const System::Word GATT_CHARACTERISTIC_ANAEROBIC_HEART_RATE_LOWER_LIMIT = System::Word(0x2a81);
static const System::Word GATT_CHARACTERISTIC_ANAEROBIC_HEART_RATE_UPPER_LIMIT = System::Word(0x2a82);
static const System::Word GATT_CHARACTERISTIC_ANAEROBIC_TRESHOLD = System::Word(0x2a83);
static const System::Word GATT_CHARACTERISTIC_AEROBIC_HEART_RATE_UPPER_LIMIT = System::Word(0x2a84);
static const System::Word GATT_CHARACTERISTIC_DATE_OF_BIRTH = System::Word(0x2a85);
static const System::Word GATT_CHARACTERISTIC_DATE_OF_TRESHOLD_ASSESSMENT = System::Word(0x2a86);
static const System::Word GATT_CHARACTERISTIC_EMAIL_ADDRESS = System::Word(0x2a87);
static const System::Word GATT_CHARACTERISTIC_FAT_BURN_HEART_RATE_LOWER_LIMIT = System::Word(0x2a88);
static const System::Word GATT_CHARACTERISTIC_FAT_BURN_HEART_RATE_UPPER_LIMIT = System::Word(0x2a89);
static const System::Word GATT_CHARACTERISTIC_FIRST_NAME = System::Word(0x2a8a);
static const System::Word GATT_CHARACTERISTIC_FIVE_ZONE_HEART_RATE_LIMITS = System::Word(0x2a8b);
static const System::Word GATT_CHARACTERISTIC_GENDER = System::Word(0x2a8c);
static const System::Word GATT_CHARACTERISTIC_HEART_RATE_MAX = System::Word(0x2a8d);
static const System::Word GATT_CHARACTERISTIC_HEIGHT = System::Word(0x2a8e);
static const System::Word GATT_CHARACTERISTIC_HIP_CIRCUMFERENCE = System::Word(0x2a8f);
static const System::Word GATT_CHARACTERISTIC_LAST_NAME = System::Word(0x2a90);
static const System::Word GATT_CHARACTERISTIC_MAXIMUM_RECOMMENDED_HEART_RATE = System::Word(0x2a91);
static const System::Word GATT_CHARACTERISTIC_RESTING_HEART_RATE = System::Word(0x2a92);
static const System::Word GATT_CHARACTERISTIC_SPORT_TYPE_FOR_AEROBIC_AND_ANAEROBIC_THRESHOLDS = System::Word(0x2a93);
static const System::Word GATT_CHARACTERISTIC_THREE_ZONE_HEART_RATE_LIMITS = System::Word(0x2a94);
static const System::Word GATT_CHARACTERISTIC_TWO_ZONE_HEART_RATE_LIMITS = System::Word(0x2a95);
static const System::Word GATT_CHARACTERISTIC_VO2_MAX = System::Word(0x2a96);
static const System::Word GATT_CHARACTERISTIC_WAIST_CIRCUMFERENCE = System::Word(0x2a97);
static const System::Word GATT_CHARACTERISTIC_WEIGHT = System::Word(0x2a98);
static const System::Word GATT_CHARACTERISTIC_DATABASE_CHANGE_INCREMENT = System::Word(0x2a99);
static const System::Word GATT_CHARACTERISTIC_USER_INDEX = System::Word(0x2a9a);
static const System::Word GATT_CHARACTERISTIC_BODY_COMPOSITION_FEATURE = System::Word(0x2a9b);
static const System::Word GATT_CHARACTERISTIC_BODY_COMPOSITION_MEASUREMENT = System::Word(0x2a9c);
static const System::Word GATT_CHARACTERISTIC_WEIGHT_MEASUREMENT = System::Word(0x2a9d);
static const System::Word GATT_CHARACTERISTIC_WEIGHT_SCALE_FEATURE = System::Word(0x2a9e);
static const System::Word GATT_CHARACTERISTIC_USER_CONTROL_POINT = System::Word(0x2a9f);
static const System::Word GATT_CHARACTERISTIC_MAGINETIC_FLUX_DENSITY_2D = System::Word(0x2aa0);
static const System::Word GATT_CHARACTERISTIC_MAGINETIC_FLUX_DENSITY_3D = System::Word(0x2aa1);
static const System::Word GATT_CHARACTERISTIC_LANGUAGE = System::Word(0x2aa2);
static const System::Word GATT_CHARACTERISTIC_BAROMETRIC_PRESSURE_TREND = System::Word(0x2aa3);
static const System::Word GATT_CHARACTERISTIC_BOND_MANAGEMENT_CONTROL_POINT = System::Word(0x2aa4);
static const System::Word GATT_CHARACTERISTIC_BOND_MANAGEMENT_FEATURE = System::Word(0x2aa5);
static const System::Word GATT_CHARACTERISTIC_CENTRAL_ADDRESS_RESOLUTION = System::Word(0x2aa6);
static const System::Word GATT_CHARACTERISTIC_CGM_MEASUREMENT = System::Word(0x2aa7);
static const System::Word GATT_CHARACTERISTIC_CGM_FEATURE = System::Word(0x2aa8);
static const System::Word GATT_CHARACTERISTIC_CGM_STATUS = System::Word(0x2aa9);
static const System::Word GATT_CHARACTERISTIC_CGM_SESSION_START_TIME = System::Word(0x2aaa);
static const System::Word GATT_CHARACTERISTIC_CGM_SESSION_RUN_TIME = System::Word(0x2aab);
static const System::Word GATT_CHARACTERISTIC_CGM_SPECIFIC_OPS_CONTROL_POINT = System::Word(0x2aac);
static const System::Word GATT_CHARACTERISTIC_INDOOR_POSITIONING_CONFIGURATION = System::Word(0x2aad);
static const System::Word GATT_CHARACTERISTIC_LATITUDE = System::Word(0x2aae);
static const System::Word GATT_CHARACTERISTIC_LONGITUDE = System::Word(0x2aaf);
static const System::Word GATT_CHARACTERISTIC_LOCAL_NORTH_COORDINATE = System::Word(0x2ab0);
static const System::Word GATT_CHARACTERISTIC_LOCAL_EAST_COORDINATE = System::Word(0x2ab1);
static const System::Word GATT_CHARACTERISTIC_FLOOR_NUMBER = System::Word(0x2ab2);
static const System::Word GATT_CHARACTERISTIC_ALTITUDE = System::Word(0x2ab3);
static const System::Word GATT_CHARACTERISTIC_UNCERTAINTY = System::Word(0x2ab4);
static const System::Word GATT_CHARACTERISTIC_LOCATION_NAME = System::Word(0x2ab5);
static const System::Word GATT_CHARACTERISTIC_URI = System::Word(0x2ab6);
static const System::Word GATT_CHARACTERISTIC_HTTP_HEADERS = System::Word(0x2ab7);
static const System::Word GATT_CHARACTERISTIC_HTTP_STATUS_CODE = System::Word(0x2ab8);
static const System::Word GATT_CHARACTERISTIC_HTTP_ENTITY_BODY = System::Word(0x2ab9);
static const System::Word GATT_CHARACTERISTIC_HTTP_CONTROL_POINT = System::Word(0x2aba);
static const System::Word GATT_CHARACTERISTIC_HTTPS_SECURITY = System::Word(0x2abb);
static const System::Word GATT_CHARACTERISTIC_TDS_CONTROL_POINT = System::Word(0x2abc);
static const System::Word GATT_CHARACTERISTIC_OTS_FEATURE = System::Word(0x2abd);
static const System::Word GATT_CHARACTERISTIC_OBJECT_NAME = System::Word(0x2abe);
static const System::Word GATT_CHARACTERISTIC_OBJECT_TYPE = System::Word(0x2abf);
static const System::Word GATT_CHARACTERISTIC_OBJECT_SIZE = System::Word(0x2ac0);
static const System::Word GATT_CHARACTERISTIC_OBJECT_FIRST_CREATED = System::Word(0x2ac1);
static const System::Word GATT_CHARACTERISTIC_OBJECT_LEAST_MODIFIED = System::Word(0x2ac2);
static const System::Word GATT_CHARACTERISTIC_OBJECT_ID = System::Word(0x2ac3);
static const System::Word GATT_CHARACTERISTIC_OBJECT_PROPERTIES = System::Word(0x2ac4);
static const System::Word GATT_CHARACTERISTIC_OBJECT_ACTION_CONTROL_POINT = System::Word(0x2ac5);
static const System::Word GATT_CHARACTERISTIC_OBJECT_LIST_CONTROL_POINT = System::Word(0x2ac6);
static const System::Word GATT_CHARACTERISTIC_OBJECT_LIST_FILTER = System::Word(0x2ac7);
static const System::Word GATT_CHARACTERISTIC_OBJECT_CHANGED = System::Word(0x2ac8);
static const System::Word GATT_CHARACTERISTIC_RESOLVABLE_PRIVATE_ADDRESS_ONLY = System::Word(0x2ac9);
static const System::Word GATT_CHARACTERISTIC_FITNESS_MACHINE_FEATURE = System::Word(0x2acc);
static const System::Word GATT_CHARACTERISTIC_TREADMILL_DATA = System::Word(0x2acd);
static const System::Word GATT_CHARACTERISTIC_CROSS_TRAINER_DATA = System::Word(0x2ace);
static const System::Word GATT_CHARACTERISTIC_STEP_CLIMBER_DATA = System::Word(0x2acf);
static const System::Word GATT_CHARACTERISTIC_STAIR_CLIMBER_DATA = System::Word(0x2ad0);
static const System::Word GATT_CHARACTERISTIC_ROWER_DATA = System::Word(0x2ad1);
static const System::Word GATT_CHARACTERISTIC_INDOOR_BIKE_DATA = System::Word(0x2ad2);
static const System::Word GATT_CHARACTERISTIC_TRAINING_STATUS = System::Word(0x2ad3);
static const System::Word GATT_CHARACTERISTIC_SUPPORTED_SPEED_RANGE = System::Word(0x2ad4);
static const System::Word GATT_CHARACTERISTIC_SUPPORTED_INCLINATION_RANGE = System::Word(0x2ad5);
static const System::Word GATT_CHARACTERISTIC_SUPPORTED_RESISTANCE_LEVEL_RANGE = System::Word(0x2ad6);
static const System::Word GATT_CHARACTERISTIC_SUPPORTED_HEART_RATE_RANGE = System::Word(0x2ad7);
static const System::Word GATT_CHARACTERISTIC_SUPPORTED_POWER_RANGE = System::Word(0x2ad8);
static const System::Word GATT_CHARACTERISTIC_FITNESS_MACHINE_CONTROL_POINT = System::Word(0x2ad9);
static const System::Word GATT_CHARACTERISTIC_FITNESS_MACHINE_STATUS = System::Word(0x2ada);
static const System::Word GATT_CHARACTERISTIC_MESH_PROVISIONING_DATA_IN = System::Word(0x2adb);
static const System::Word GATT_CHARACTERISTIC_MESH_PROVISIONING_DATA_OUT = System::Word(0x2adc);
static const System::Word GATT_CHARACTERISTIC_MESH_PROXY_DATA_IN = System::Word(0x2add);
static const System::Word GATT_CHARACTERISTIC_MESH_PROXY_DATA_OUT = System::Word(0x2ade);
static const System::Word GATT_CHARACTERISTIC_AVERAGE_CURRENT = System::Word(0x2ae0);
static const System::Word GATT_CHARACTERISTIC_AVERAGE_VOLTAGE = System::Word(0x2ae1);
static const System::Word GATT_CHARACTERISTIC_BOOLEAN = System::Word(0x2ae2);
static const System::Word GATT_CHARACTERISTIC_CHROMATIC_DISTANCE_FROM_PLANCKIAN = System::Word(0x2ae3);
static const System::Word GATT_CHARACTERISTIC_CHROMATICITY_COORDINATES = System::Word(0x2ae4);
static const System::Word GATT_CHARACTERISTIC_CHROMATICITY_IN_CCT_AND_DUV_VALUES = System::Word(0x2ae5);
static const System::Word GATT_CHARACTERISTIC_CHROMATICITY_TOLERANCE = System::Word(0x2ae6);
static const System::Word GATT_CHARACTERISTIC_CIE_COLOR_RENDERING_INDEX = System::Word(0x2ae7);
static const System::Word GATT_CHARACTERISTIC_COEFFICIENT = System::Word(0x2ae8);
static const System::Word GATT_CHARACTERISTIC_CORRELATED_COLOR_TEMPERATURE = System::Word(0x2ae9);
static const System::Word GATT_CHARACTERISTIC_COUNT_16 = System::Word(0x2aea);
static const System::Word GATT_CHARACTERISTIC_COUNT_24 = System::Word(0x2aeb);
static const System::Word GATT_CHARACTERISTIC_COUNTRY_CODE = System::Word(0x2aec);
static const System::Word GATT_CHARACTERISTIC_DATE_UTC = System::Word(0x2aed);
static const System::Word GATT_CHARACTERISTIC_ELECTRIC_CURRENT = System::Word(0x2aee);
static const System::Word GATT_CHARACTERISTIC_ELECTRIC_CURRENT_RANGE = System::Word(0x2aef);
static const System::Word GATT_CHARACTERISTIC_ELECTRIC_CURRENT_SPECIFICATION = System::Word(0x2af0);
static const System::Word GATT_CHARACTERISTIC_ELECTRIC_CURRENT_STATISTICS = System::Word(0x2af1);
static const System::Word GATT_CHARACTERISTIC_ENERGY = System::Word(0x2af2);
static const System::Word GATT_CHARACTERISTIC_ENERGY_IN_PERIOD_OF_DAY = System::Word(0x2af3);
static const System::Word GATT_CHARACTERISTIC_EVENT_STATISTICS = System::Word(0x2af4);
static const System::Word GATT_CHARACTERISTIC_FIXED_STRING_16 = System::Word(0x2af5);
static const System::Word GATT_CHARACTERISTIC_FIXED_STRING_24 = System::Word(0x2af6);
static const System::Word GATT_CHARACTERISTIC_FIXED_STRING_36 = System::Word(0x2af7);
static const System::Word GATT_CHARACTERISTIC_FIXED_STRING_8 = System::Word(0x2af8);
static const System::Word GATT_CHARACTERISTIC_GENERIC_LEVEL = System::Word(0x2af9);
static const System::Word GATT_CHARACTERISTIC_GLOBAL_TRADE_ITEM_NUMBER = System::Word(0x2afa);
static const System::Word GATT_CHARACTERISTIC_ILLUMINANCE = System::Word(0x2afb);
static const System::Word GATT_CHARACTERISTIC_LUMINOUS_EFFICACY = System::Word(0x2afc);
static const System::Word GATT_CHARACTERISTIC_LUMINOUS_ENERGY = System::Word(0x2afd);
static const System::Word GATT_CHARACTERISTIC_LUMINOUS_EXPOSURE = System::Word(0x2afe);
static const System::Word GATT_CHARACTERISTIC_LUMINOUS_FLUX = System::Word(0x2aff);
static const System::Word GATT_CHARACTERISTIC_LUMINOUS_FLUX_RANGE = System::Word(0x2b00);
static const System::Word GATT_CHARACTERISTIC_LUMINOUS_INTENSITY = System::Word(0x2b01);
static const System::Word GATT_CHARACTERISTIC_MASS_FLOW = System::Word(0x2b02);
static const System::Word GATT_CHARACTERISTIC_PERCEIVED_LIGHTNESS = System::Word(0x2b03);
static const System::Word GATT_CHARACTERISTIC_PERCENTAGE_8 = System::Word(0x2b04);
static const System::Word GATT_CHARACTERISTIC_POWER = System::Word(0x2b05);
static const System::Word GATT_CHARACTERISTIC_POWER_SPECIFICATION = System::Word(0x2b06);
static const System::Word GATT_CHARACTERISTIC_RELATIVE_RUNTIME_IN_CURRENT_RANGE = System::Word(0x2b07);
static const System::Word GATT_CHARACTERISTIC_RELATIVE_RUNTIME_IN_GENERIC_LEVEL_RANGE = System::Word(0x2b08);
static const System::Word GATT_CHARACTERISTIC_RELATIVE_VALUE_IN_VOLTAGE_RANGE = System::Word(0x2b09);
static const System::Word GATT_CHARACTERISTIC_RELATIVE_VALUE_IN_ILLUMINANCE_RANGE = System::Word(0x2b0a);
static const System::Word GATT_CHARACTERISTIC_RELATIVE_VALUE_IN_PERIOD_OF_DAY = System::Word(0x2b0b);
static const System::Word GATT_CHARACTERISTIC_RELATIVE_VALUE_IN_TEMPERATURE_RANGE = System::Word(0x2b0c);
static const System::Word GATT_CHARACTERISTIC_TEMPERATURE_8 = System::Word(0x2b0d);
static const System::Word GATT_CHARACTERISTIC_TEMPERATURE_8_IN_PERIOD_OF_DAY = System::Word(0x2b0e);
static const System::Word GATT_CHARACTERISTIC_TEMPERATURE_8_STATISTICS = System::Word(0x2b0f);
static const System::Word GATT_CHARACTERISTIC_TEMPERATURE_RANGE = System::Word(0x2b10);
static const System::Word GATT_CHARACTERISTIC_TEMPERATURE_STATISTICS = System::Word(0x2b11);
static const System::Word GATT_CHARACTERISTIC_TIME_DECIHOUR_8 = System::Word(0x2b12);
static const System::Word GATT_CHARACTERISTIC_TIME_EXPONENTIAL_8 = System::Word(0x2b13);
static const System::Word GATT_CHARACTERISTIC_TIME_HOUR_24 = System::Word(0x2b14);
static const System::Word GATT_CHARACTERISTIC_TIME_MILLISECOND_24 = System::Word(0x2b15);
static const System::Word GATT_CHARACTERISTIC_TIME_SECOND_16 = System::Word(0x2b16);
static const System::Word GATT_CHARACTERISTIC_TIME_SECOND_8 = System::Word(0x2b17);
static const System::Word GATT_CHARACTERISTIC_VOLTAGE = System::Word(0x2b18);
static const System::Word GATT_CHARACTERISTIC_VOLTAGE_SPECIFICATION = System::Word(0x2b19);
static const System::Word GATT_CHARACTERISTIC_VOLTAGE_STATISTICS = System::Word(0x2b1a);
static const System::Word GATT_CHARACTERISTIC_VOLUME_FLOW = System::Word(0x2b1b);
static const System::Word GATT_CHARACTERISTIC_CHROMATICITY_COORDINATE = System::Word(0x2b1c);
static const System::Word GATT_CHARACTERISTIC_RC_FEATURE = System::Word(0x2b1d);
static const System::Word GATT_CHARACTERISTIC_RC_SETTINGS = System::Word(0x2b1e);
static const System::Word GATT_CHARACTERISTIC_RECONNECTION_CONFIGURATION_CONTROL_POINT = System::Word(0x2b1f);
static const System::Word GATT_CHARACTERISTIC_IID_STATUS_CHANGED = System::Word(0x2b20);
static const System::Word GATT_CHARACTERISTIC_IID_STATUS = System::Word(0x2b21);
static const System::Word GATT_CHARACTERISTIC_IID_ANNUNCIATION_STATUS = System::Word(0x2b22);
static const System::Word GATT_CHARACTERISTIC_IID_FEATURES = System::Word(0x2b23);
static const System::Word GATT_CHARACTERISTIC_IID_STATUS_READER_CONTROL_POINT = System::Word(0x2b24);
static const System::Word GATT_CHARACTERISTIC_IID_COMMAND_CONTROL_POINT = System::Word(0x2b25);
static const System::Word GATT_CHARACTERISTIC_IID_COMMAND_DATA = System::Word(0x2b26);
static const System::Word GATT_CHARACTERISTIC_IID_RECORD_ACCESS_CONTROL_POINT = System::Word(0x2b27);
static const System::Word GATT_CHARACTERISTIC_IID_HISTORY_DATA = System::Word(0x2b28);
static const System::Word GATT_CHARACTERISTIC_CLIENT_SUPPORTED_FEATURES = System::Word(0x2b29);
static const System::Word GATT_CHARACTERISTIC_DATABASE_HASH = System::Word(0x2b2a);
static const System::Word GATT_CHARACTERISTIC_BSS_CONTROL_POINT = System::Word(0x2b2b);
static const System::Word GATT_CHARACTERISTIC_BSS_RESPONSE = System::Word(0x2b2c);
static const System::Word GATT_CHARACTERISTIC_EMERGENCY_ID = System::Word(0x2b2d);
static const System::Word GATT_CHARACTERISTIC_EMERGENCY_TEXT = System::Word(0x2b2e);
static const System::Word GATT_CHARACTERISTIC_ACS_STATUS = System::Word(0x2b2f);
static const System::Word GATT_CHARACTERISTIC_ACS_DATA_IN = System::Word(0x2b30);
static const System::Word GATT_CHARACTERISTIC_ACS_DATA_OUT_NOTIFY = System::Word(0x2b31);
static const System::Word GATT_CHARACTERISTIC_ACS_DATA_OUT_INDICATE = System::Word(0x2b32);
static const System::Word GATT_CHARACTERISTIC_ACS_CONTROL_POINT = System::Word(0x2b33);
static const System::Word GATT_CHARACTERISTIC_ENHANCED_BLOOD_PRESSURE_MEASUREMENT = System::Word(0x2b34);
static const System::Word GATT_CHARACTERISTIC_ENHANCED_INTERMEDIATE_CUFF_PRESSURE = System::Word(0x2b35);
static const System::Word GATT_CHARACTERISTIC_BLOOD_PRESSURE_RECORD = System::Word(0x2b36);
static const System::Word GATT_CHARACTERISTIC_REGISTERED_USER_DATA = System::Word(0x2b37);
static const System::Word GATT_CHARACTERISTIC_BR_EDR_HANDOVER_DATA = System::Word(0x2b38);
static const System::Word GATT_CHARACTERISTIC_BLUETOOTH_SIG_DATA = System::Word(0x2b39);
static const System::Word GATT_CHARACTERISTIC_SERVER_SUPPORTED_FEATURE = System::Word(0x2b3a);
static const System::Word GATT_CHARACTERISTIC_PHYSICAL_ACTIVITY_MONITOR_FEATURES = System::Word(0x2b3b);
static const System::Word GATT_CHARACTERISTIC_GENERAL_ACTIVITY_INSTANTANEOUS_DATA = System::Word(0x2b3c);
static const System::Word GATT_CHARACTERISTIC_GENERAL_ACTIVITY_SUMMARY_DATA = System::Word(0x2b3d);
static const System::Word GATT_CHARACTERISTIC_CARDIO_RESPIRATORY_ACTIVITY_INSTANTANEOUS_DATA = System::Word(0x2b3e);
static const System::Word GATT_CHARACTERISTIC_CARDIO_RESPIRATORY_ACTIVITY_SUMMARY_DATA = System::Word(0x2b3f);
static const System::Word GATT_CHARACTERISTIC_STEP_COUNTER_ACTIVITY_SUMMARY_DATA = System::Word(0x2b40);
static const System::Word GATT_CHARACTERISTIC_SLEEP_ACTIVITY_INSTANTANEOUS_DATA = System::Word(0x2b41);
static const System::Word GATT_CHARACTERISTIC_SLEEP_ACTIVITY_SUMMARY_DATA = System::Word(0x2b42);
static const System::Word GATT_CHARACTERISTIC_PHYSICAL_ACTIVITY_MONITOR_CONTROL_POINT = System::Word(0x2b43);
static const System::Word GATT_CHARACTERISTIC_PHYSICAL_ACTIVITY_CURRENT_SESSION = System::Word(0x2b44);
static const System::Word GATT_CHARACTERISTIC_PHYSICAL_ACTIVITY_SESSION_DESCRIPTOR = System::Word(0x2b45);
static const System::Word GATT_CHARACTERISTIC_PREFERRED_UNITS = System::Word(0x2b46);
static const System::Word GATT_CHARACTERISTIC_HIGH_RESOLUTION_HEIGHT = System::Word(0x2b47);
static const System::Word GATT_CHARACTERISTIC_MIDDLE_NAME = System::Word(0x2b48);
static const System::Word GATT_CHARACTERISTIC_STRIDE_LENGTH = System::Word(0x2b49);
static const System::Word GATT_CHARACTERISTIC_HANDEDNESS = System::Word(0x2b4a);
static const System::Word GATT_CHARACTERISTIC_DEVICE_WEARING_POSITION = System::Word(0x2b4b);
static const System::Word GATT_CHARACTERISTIC_FOUR_ZONE_HEART_RATE_LIMITS = System::Word(0x2b4c);
static const System::Word GATT_CHARACTERISTIC_HIGH_INTENSITY_EXERCISE_THRESHOLD = System::Word(0x2b4d);
static const System::Word GATT_CHARACTERISTIC_ACTIVITY_GOAL = System::Word(0x2b4e);
static const System::Word GATT_CHARACTERISTIC_SEDENTARY_INTERVAL_NOTIFICATION = System::Word(0x2b4f);
static const System::Word GATT_CHARACTERISTIC_CALORIC_INTAKE = System::Word(0x2b50);
static const System::Word GATT_CHARACTERISTIC_TMAP_ROLE = System::Word(0x2b51);
static const System::Word GATT_CHARACTERISTIC_AUDIO_INPUT_STATE = System::Word(0x2b77);
static const System::Word GATT_CHARACTERISTIC_GAIN_SETTINGS_ATTRIBUTE = System::Word(0x2b78);
static const System::Word GATT_CHARACTERISTIC_AUDIO_INPUT_TYPE = System::Word(0x2b79);
static const System::Word GATT_CHARACTERISTIC_AUDIO_INPUT_STATUS = System::Word(0x2b7a);
static const System::Word GATT_CHARACTERISTIC_AUDIO_INPUT_CONTROL_POINT = System::Word(0x2b7b);
static const System::Word GATT_CHARACTERISTIC_AUDIO_INPUT_DESCRIPTION = System::Word(0x2b7c);
static const System::Word GATT_CHARACTERISTIC_VOLUME_STATE = System::Word(0x2b7d);
static const System::Word GATT_CHARACTERISTIC_VOLUME_CONTROL_POINT = System::Word(0x2b7e);
static const System::Word GATT_CHARACTERISTIC_VOLUME_FLAGS = System::Word(0x2b7f);
static const System::Word GATT_CHARACTERISTIC_VOLUME_OFFSET_STATE = System::Word(0x2b80);
static const System::Word GATT_CHARACTERISTIC_AUDIO_LOCATION = System::Word(0x2b81);
static const System::Word GATT_CHARACTERISTIC_VOLUME_OFFSET_CONTROL_POINT = System::Word(0x2b82);
static const System::Word GATT_CHARACTERISTIC_AUDIO_OUTPUT_DESCRIPTION = System::Word(0x2b83);
static const System::Word GATT_CHARACTERISTIC_SET_IDENTITY_RESOLVING_KEY = System::Word(0x2b84);
static const System::Word GATT_CHARACTERISTIC_COORDINATED_SET_SIZE = System::Word(0x2b85);
static const System::Word GATT_CHARACTERISTIC_SET_MEMBER_LOCK = System::Word(0x2b86);
static const System::Word GATT_CHARACTERISTIC_SET_MEMBER_RANK = System::Word(0x2b87);
static const System::Word GATT_CHARACTERISTIC_ENCRYPTED_DATA_KEY_MATERIAL = System::Word(0x2b88);
static const System::Word GATT_CHARACTERISTIC_APPARENT_ENERGY_32 = System::Word(0x2b89);
static const System::Word GATT_CHARACTERISTIC_APPARENT_POWER = System::Word(0x2b8a);
static const System::Word GATT_CHARACTERISTIC_LIVE_HEALTH_OBSERVATIONS = System::Word(0x2b8b);
static const System::Word GATT_CHARACTERISTIC_CO_CONCENTRATION = System::Word(0x2b8c);
static const System::Word GATT_CHARACTERISTIC_COSINE_OF_ANGLE = System::Word(0x2b8d);
static const System::Word GATT_CHARACTERISTIC_DEVICE_TIME_FEATURE = System::Word(0x2b8e);
static const System::Word GATT_CHARACTERISTIC_DEVICE_TIME_PARAMETERS = System::Word(0x2b8f);
static const System::Word GATT_CHARACTERISTIC_DEVICE_TIME = System::Word(0x2b90);
static const System::Word GATT_CHARACTERISTIC_DEVICE_TIME_CONTROL_POINT = System::Word(0x2b91);
static const System::Word GATT_CHARACTERISTIC_TIME_CHANGE_LOG_DATA = System::Word(0x2b92);
static const System::Word GATT_CHARACTERISTIC_MEDIA_PLAYER_NAME = System::Word(0x2b93);
static const System::Word GATT_CHARACTERISTIC_MEDIA_PLAYER_ICON_OBJECT_ID = System::Word(0x2b94);
static const System::Word GATT_CHARACTERISTIC_MEDIA_PLAYER_ICON_URL = System::Word(0x2b95);
static const System::Word GATT_CHARACTERISTIC_TRACK_CHANGED = System::Word(0x2b96);
static const System::Word GATT_CHARACTERISTIC_TRACK_TITLE = System::Word(0x2b97);
static const System::Word GATT_CHARACTERISTIC_TRACK_DURATION = System::Word(0x2b98);
static const System::Word GATT_CHARACTERISTIC_TRACK_POSITION = System::Word(0x2b99);
static const System::Word GATT_CHARACTERISTIC_PLAYBACK_SPEED = System::Word(0x2b9a);
static const System::Word GATT_CHARACTERISTIC_SEEKING_SPEED = System::Word(0x2b9b);
static const System::Word GATT_CHARACTERISTIC_CURRENT_TRACK_SEGMENTS_OBJECT_ID = System::Word(0x2b9c);
static const System::Word GATT_CHARACTERISTIC_CURRENT_TRACK_OBJECT_ID = System::Word(0x2b9d);
static const System::Word GATT_CHARACTERISTIC_NEXT_TRACK_OBJECT_ID = System::Word(0x2b9e);
static const System::Word GATT_CHARACTERISTIC_PARENT_GROUP_OBJECT_ID = System::Word(0x2b9f);
static const System::Word GATT_CHARACTERISTIC_CURRENT_GROUP_OBJECT_ID = System::Word(0x2ba0);
static const System::Word GATT_CHARACTERISTIC_PLAYING_ORDER = System::Word(0x2ba1);
static const System::Word GATT_CHARACTERISTIC_PLAYING_ORDERS_SUPPORTED = System::Word(0x2ba2);
static const System::Word GATT_CHARACTERISTIC_MEDIA_STATE = System::Word(0x2ba3);
static const System::Word GATT_CHARACTERISTIC_MEDIA_CONTROL_POINT = System::Word(0x2ba4);
static const System::Word GATT_CHARACTERISTIC_MEDIA_CONTROL_POINT_OPCODES_SUPPORTED = System::Word(0x2ba5);
static const System::Word GATT_CHARACTERISTIC_SEARCH_RESULTS_OBJECT_ID = System::Word(0x2ba6);
static const System::Word GATT_CHARACTERISTIC_SEARCH_CONTROL_POINT = System::Word(0x2ba7);
static const System::Word GATT_CHARACTERISTIC_ENERGY_32 = System::Word(0x2ba8);
static const System::Word GATT_CHARACTERISTIC_MEDIA_PLAYER_ICON_OBJECT_TYPE = System::Word(0x2ba9);
static const System::Word GATT_CHARACTERISTIC_TRACK_SEGMENTS_OBJECT_TYPE = System::Word(0x2baa);
static const System::Word GATT_CHARACTERISTIC_TRACK_OBJECT_TYPE = System::Word(0x2bab);
static const System::Word GATT_CHARACTERISTIC_GROUP_OBJECT_TYPE = System::Word(0x2bac);
static const System::Word GATT_CHARACTERISTIC_CONSTANT_TONE_EXTENSION_ENABLE = System::Word(0x2bad);
static const System::Word GATT_CHARACTERISTIC_ADVERTISING_CONSTANT_TONE_EXTENSION_MINIMUM_LENGTH = System::Word(0x2bae);
static const System::Word GATT_CHARACTERISTIC_ADVERTISING_CONSTANT_TONE_EXTENSION_MINIMUM_TRANSMIT_COUNT = System::Word(0x2baf);
static const System::Word GATT_CHARACTERISTIC_ADVERTISING_CONSTANT_TONE_EXTENSION_TRANSMIT_DURATION = System::Word(0x2bb0);
static const System::Word GATT_CHARACTERISTIC_ADVERTISING_CONSTANT_TONE_EXTENSION_INTERVAL = System::Word(0x2bb1);
static const System::Word GATT_CHARACTERISTIC_ADVERTISING_CONSTANT_TONE_EXTENSION_PHY = System::Word(0x2bb2);
static const System::Word GATT_CHARACTERISTIC_BEARER_PROVIDER_NAME = System::Word(0x2bb3);
static const System::Word GATT_CHARACTERISTIC_BEARER_UCI = System::Word(0x2bb4);
static const System::Word GATT_CHARACTERISTIC_BEARER_TECHNOLOGY = System::Word(0x2bb5);
static const System::Word GATT_CHARACTERISTIC_BEARER_URI_SCHEMES_SUPPORTED_LIST = System::Word(0x2bb6);
static const System::Word GATT_CHARACTERISTIC_BEARER_SIGNAL_STRENGTH = System::Word(0x2bb7);
static const System::Word GATT_CHARACTERISTIC_BEARER_SIGNAL_STRENGTH_REPORTING_INTERVAL = System::Word(0x2bb8);
static const System::Word GATT_CHARACTERISTIC_BEARER_LIST_CURRENT_CALLS = System::Word(0x2bb9);
static const System::Word GATT_CHARACTERISTIC_CONTENT_CONTROL_ID = System::Word(0x2bba);
static const System::Word GATT_CHARACTERISTIC_STATUS_FLAGS = System::Word(0x2bbb);
static const System::Word GATT_CHARACTERISTIC_INCOMING_CALL_TARGET_BEARER_URI = System::Word(0x2bbc);
static const System::Word GATT_CHARACTERISTIC_CALL_STATE = System::Word(0x2bbd);
static const System::Word GATT_CHARACTERISTIC_CALL_CONTROL_POINT = System::Word(0x2bbe);
static const System::Word GATT_CHARACTERISTIC_CALL_CONTROL_POINT_OPTIONAL_OPCODES = System::Word(0x2bbf);
static const System::Word GATT_CHARACTERISTIC_TERMINATION_REASON = System::Word(0x2bc0);
static const System::Word GATT_CHARACTERISTIC_INCOMING_CALL = System::Word(0x2bc1);
static const System::Word GATT_CHARACTERISTIC_CALL_FRIENDLY_NAME = System::Word(0x2bc2);
static const System::Word GATT_CHARACTERISTIC_MUTE = System::Word(0x2bc3);
static const System::Word GATT_CHARACTERISTIC_SINK_ASE = System::Word(0x2bc4);
static const System::Word GATT_CHARACTERISTIC_SOURCE_ASE = System::Word(0x2bc5);
static const System::Word GATT_CHARACTERISTIC_ASE_CONTROL_POINT = System::Word(0x2bc6);
static const System::Word GATT_CHARACTERISTIC_BROADCAST_AUDIO_SCAN_CONTROL_POINT = System::Word(0x2bc7);
static const System::Word GATT_CHARACTERISTIC_BROADCAST_RECEIVE_STATE = System::Word(0x2bc8);
static const System::Word GATT_CHARACTERISTIC_SINK_PAC = System::Word(0x2bc9);
static const System::Word GATT_CHARACTERISTIC_SINK_AUDIO_LOCATIONS = System::Word(0x2bca);
static const System::Word GATT_CHARACTERISTIC_SOURCE_PAC = System::Word(0x2bcb);
static const System::Word GATT_CHARACTERISTIC_SOURCE_AUDIO_LOCATIONS = System::Word(0x2bcc);
static const System::Word GATT_CHARACTERISTIC_AVAILABLE_AUDIO_CONTEXTS = System::Word(0x2bcd);
static const System::Word GATT_CHARACTERISTIC_SUPPORTED_AUDIO_CONTEXTS = System::Word(0x2bce);
static const System::Word GATT_CHARACTERISTIC_AMMONIA_CONCENTRATION = System::Word(0x2bcf);
static const System::Word GATT_CHARACTERISTIC_CARBON_MONOXIDE_CONCENTRATION = System::Word(0x2bd0);
static const System::Word GATT_CHARACTERISTIC_METHANE_CONCENTRATION = System::Word(0x2bd1);
static const System::Word GATT_CHARACTERISTIC_NITROGEN_DIOXIDE_CONCENTRATION = System::Word(0x2bd2);
static const System::Word GATT_CHARACTERISTIC_NON_METHANE_VOLATILE_ORGANIC_COMPOUNDS_CONCENTRATION = System::Word(0x2bd3);
static const System::Word GATT_CHARACTERISTIC_OZONE_CONCENTRATION = System::Word(0x2bd4);
static const System::Word GATT_CHARACTERISTIC_PARTICULATE_MATTER_PM1_CONCENTRATION = System::Word(0x2bd5);
static const System::Word GATT_CHARACTERISTIC_PARTICULATE_MATTER_PM25_CONCENTRATION = System::Word(0x2bd6);
static const System::Word GATT_CHARACTERISTIC_PARTICULATE_MATTER_PM10_CONCENTRATION = System::Word(0x2bd7);
static const System::Word GATT_CHARACTERISTIC_SULFUR_DIOXIDE_CONCENTRATION = System::Word(0x2bd8);
static const System::Word GATT_CHARACTERISTIC_SULFUR_HEXAFLUORIDE_CONCENTRATION = System::Word(0x2bd9);
static const System::Word GATT_CHARACTERISTIC_HEARING_AID_FEATURES = System::Word(0x2bda);
static const System::Word GATT_CHARACTERISTIC_HEARING_AID_PRESENT_CONTROL_POINT = System::Word(0x2bdb);
static const System::Word GATT_CHARACTERISTIC_ACTIVE_PRESENT_INDEX = System::Word(0x2bdc);
static const System::Word GATT_CHARACTERISTIC_STORED_HEALTH_OBSERVATIONS = System::Word(0x2bdd);
static const System::Word GATT_CHARACTERISTIC_FIXED_STRING_64 = System::Word(0x2bde);
static const System::Word GATT_CHARACTERISTIC_HIGH_TEMPERATURE = System::Word(0x2bdf);
static const System::Word GATT_CHARACTERISTIC_HIGH_VOLTAGE = System::Word(0x2be0);
static const System::Word GATT_CHARACTERISTIC_LIGHT_DISTRIBUTION = System::Word(0x2be1);
static const System::Word GATT_CHARACTERISTIC_LIGHT_OUTPUT = System::Word(0x2be2);
static const System::Word GATT_CHARACTERISTIC_LIGHT_SOURCE_TYPE = System::Word(0x2be3);
static const System::Word GATT_CHARACTERISTIC_NOISE = System::Word(0x2be4);
static const System::Word GATT_CHARACTERISTIC_RELATIVE_RUNTIME_CORRELATED_COLOR_TEMPERATURE_RANGE = System::Word(0x2be5);
static const System::Word GATT_CHARACTERISTIC_TIME_SECOND_32 = System::Word(0x2be6);
static const System::Word GATT_CHARACTERISTIC_VOC_CONCENTRATION = System::Word(0x2be7);
static const System::Word GATT_CHARACTERISTIC_VOLTAGE_FREQUENCY = System::Word(0x2be8);
static const System::Word GATT_CHARACTERISTIC_BATTERY_CRITICAL_STATUS = System::Word(0x2be9);
static const System::Word GATT_CHARACTERISTIC_BATTERY_HEALTH_STATUS = System::Word(0x2bea);
static const System::Word GATT_CHARACTERISTIC_BATTERY_HEALTH_INFORMATION = System::Word(0x2beb);
static const System::Word GATT_CHARACTERISTIC_BATTERY_INFORMATION = System::Word(0x2bec);
static const System::Word GATT_CHARACTERISTIC_BATTERY_LEVEL_STATUS = System::Word(0x2bed);
static const System::Word GATT_CHARACTERISTIC_BATTERY_TIME_STATUS = System::Word(0x2bee);
static const System::Word GATT_CHARACTERISTIC_ESTIMATED_SERVICE_DATE = System::Word(0x2bef);
static const System::Word GATT_CHARACTERISTIC_BATTERY_ENERGY_STATUS = System::Word(0x2bf0);
static const System::Word GATT_CHARACTERISTIC_OBSERVATION_SCHEDULE_CHANGED = System::Word(0x2bf1);
static const System::Word GATT_CHARACTERISTIC_CURRENT_ELAPSED_TIME = System::Word(0x2bf2);
static const System::Word GATT_CHARACTERISTIC_HEALTH_SENSOR_FEATURES = System::Word(0x2bf3);
static const System::Word GATT_CHARACTERISTIC_GHS_CONTROL_POINT = System::Word(0x2bf4);
static const System::Word GATT_CHARACTERISTIC_LE_GATT_SECURITY_LEVELS = System::Word(0x2bf5);
static const System::Word GATT_CHARACTERISTIC_ESL_ADDRESS = System::Word(0x2bf6);
static const System::Word GATT_CHARACTERISTIC_AP_SYNC_KEY_MATERIAL = System::Word(0x2bf7);
static const System::Word GATT_CHARACTERISTIC_ESL_RESPONSE_KEY_MATERIAL = System::Word(0x2bf8);
static const System::Word GATT_CHARACTERISTIC_ESL_CURRENT_ABSOLUTE_TIME = System::Word(0x2bf9);
static const System::Word GATT_CHARACTERISTIC_ESL_DISPLAY_INFORMATION = System::Word(0x2bfa);
static const System::Word GATT_CHARACTERISTIC_ESL_IMAGE_INFORMATION = System::Word(0x2bfb);
static const System::Word GATT_CHARACTERISTIC_ESL_SENSOR_INFORMATION = System::Word(0x2bfc);
static const System::Word GATT_CHARACTERISTIC_ESL_LED_INFORMATION = System::Word(0x2bfd);
static const System::Word GATT_CHARACTERISTIC_ESL_CONTROL_POINT = System::Word(0x2bfe);
static const System::Word GATT_CHARACTERISTIC_UDI_MEDICAL_DEVICES = System::Word(0x2bff);
static const System::Word GATT_CHARACTERISTIC_GMAP_ROLE = System::Word(0x2c00);
static const System::Word GATT_CHARACTERISTIC_UGG_FEATURES = System::Word(0x2c01);
static const System::Word GATT_CHARACTERISTIC_UGT_FEATURES = System::Word(0x2c02);
static const System::Word GATT_CHARACTERISTIC_BGS_FEATURES = System::Word(0x2c03);
static const System::Word GATT_CHARACTERISTIC_BGR_FEATURES = System::Word(0x2c04);
static const System::Word GATT_OBJECT_TYPE_UNSPECIFIED = System::Word(0x2aca);
static const System::Word GATT_OBJECT_TYPE_DIRECTORY_LISTING = System::Word(0x2acb);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_OFFSET = System::Int8(0x6);
static const System::Word LE_GAP_APPEARANCE_CATEGORY_MASK = System::Word(0x3ff);
static const System::Int8 LE_GAP_APPEARANCE_SUB_CATEGORY_MASK = System::Int8(0x3f);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_UNKNOWN = System::Int8(0x0);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_PHONE = System::Int8(0x1);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_COMPUTER = System::Int8(0x2);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_WATCH = System::Int8(0x3);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_CLOCK = System::Int8(0x4);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_DISPLAY = System::Int8(0x5);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_REMOTE_CONTROL = System::Int8(0x6);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_EYE_GLASSES = System::Int8(0x7);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_TAG = System::Int8(0x8);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_KEYRING = System::Int8(0x9);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_MEDIA_PLAYER = System::Int8(0xa);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_BARCODE_SCANNER = System::Int8(0xb);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_THERMOMETER = System::Int8(0xc);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_HEART_RATE_SENSOR = System::Int8(0xd);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_BLOOD_PRESSURE = System::Int8(0xe);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_HUMAN_INTERFACE_DEVICE = System::Int8(0xf);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_GLUCOSE_METER = System::Int8(0x10);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_RUNNING_WALKING_SENSOR = System::Int8(0x11);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_CYCLING = System::Int8(0x12);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_CONTROL_DEVICE = System::Int8(0x13);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_NETWORK_DEVICE = System::Int8(0x14);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_SENSOR = System::Int8(0x15);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_LIGHT_FIXTURES = System::Int8(0x16);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_FAN = System::Int8(0x17);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_HVAC = System::Int8(0x18);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_AIR_CONDITIONING = System::Int8(0x19);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_HUMIDIFIER = System::Int8(0x1a);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_HEATING = System::Int8(0x1b);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_ACCESS_CONTROL = System::Int8(0x1c);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_MOTORIZED_DEVICE = System::Int8(0x1d);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_POWER_DEVICE = System::Int8(0x1e);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_LIGHT_SOURCE = System::Int8(0x1f);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_WINDOW_COVERING = System::Int8(0x20);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_AUDIO_SINK = System::Int8(0x21);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_AUDIO_SOURCE = System::Int8(0x22);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_MOTORIZED_VEHICLE = System::Int8(0x23);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_DOMESTIC_APPLIANCE = System::Int8(0x24);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_WEARABLE_AUDIO_DEVICE = System::Int8(0x25);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_AIRCRAFT = System::Int8(0x26);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_AV_EQUIPMENT = System::Int8(0x27);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_DISPLAY_EQUIPMENT = System::Int8(0x28);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_HEARING_AID = System::Int8(0x29);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_GAMING = System::Int8(0x2a);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_SIGNAGE = System::Int8(0x2b);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_PULSE_OXIMETER = System::Int8(0x31);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_WEIGHT_SCALE = System::Int8(0x32);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_PERSONAL_MOBILITY_DEVICE = System::Int8(0x33);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_CONTINUOUS_GLUCOSE_MONITOR = System::Int8(0x34);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_INSULIN_PUMP = System::Int8(0x35);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_MEDICATION_DELIVERY = System::Int8(0x36);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_SPIROMETER = System::Int8(0x37);
static const System::Int8 LE_GAP_APPEARANCE_CATEGORY_OUTDOOR_SPORTS_ACTIVITY = System::Int8(0x51);
static const System::Int8 LE_GAP_APPEARANCE_GENERIC_UNKNOWN = System::Int8(0x0);
static const System::Int8 LE_GAP_APPEARANCE_GENERIC_PHONE = System::Int8(0x40);
static const System::Byte LE_GAP_APPEARANCE_GENERIC_COMPUTER = System::Byte(0x80);
static const System::Byte LE_GAP_APPEARANCE_DESKTOP_WORKSTATION = System::Byte(0x81);
static const System::Byte LE_GAP_APPEARANCE_SERVER_CLASS_COMPUTER = System::Byte(0x82);
static const System::Byte LE_GAP_APPEARANCE_LAPTOP = System::Byte(0x83);
static const System::Byte LE_GAP_APPEARANCE_HANDHELD_COMPUTER = System::Byte(0x84);
static const System::Byte LE_GAP_APPEARANCE_PALM_SIZE_COMPUTER = System::Byte(0x85);
static const System::Byte LE_GAP_APPEARANCE_WEARABLE_COMPUTER = System::Byte(0x86);
static const System::Byte LE_GAP_APPEARANCE_TABLET_COMPUTER = System::Byte(0x87);
static const System::Byte LE_GAP_APPEARANCE_DOCKING_STATION = System::Byte(0x88);
static const System::Byte LE_GAP_APPEARANCE_ALL_IN_ONE = System::Byte(0x89);
static const System::Byte LE_GAP_APPEARANCE_BLADE_SERVER = System::Byte(0x8a);
static const System::Byte LE_GAP_APPEARANCE_CONVERTIBLE = System::Byte(0x8b);
static const System::Byte LE_GAP_APPEARANCE_DETACHABLE = System::Byte(0x8c);
static const System::Byte LE_GAP_APPEARANCE_IOT_GATEWAY = System::Byte(0x8d);
static const System::Byte LE_GAP_APPEARANCE_MINI_PC = System::Byte(0x8e);
static const System::Byte LE_GAP_APPEARANCE_STICK_PC = System::Byte(0x8f);
static const System::Byte LE_GAP_APPEARANCE_GENERIC_WATCH = System::Byte(0xc0);
static const System::Byte LE_GAP_APPEARANCE_SPORTS_WATCH = System::Byte(0xc1);
static const System::Byte LE_GAP_APPEARANCE_SMARTWATCH = System::Byte(0xc2);
static const System::Word LE_GAP_APPEARANCE_GENERIC_CLOCK = System::Word(0x100);
static const System::Word LE_GAP_APPEARANCE_GENERIC_DISPLAY = System::Word(0x140);
static const System::Word LE_GAP_APPEARANCE_GENERIC_REMOTE_CONTROL = System::Word(0x180);
static const System::Word LE_GAP_APPEARANCE_GENERIC_EYE_GLASSES = System::Word(0x1c0);
static const System::Word LE_GAP_APPEARANCE_GENERIC_TAG = System::Word(0x200);
static const System::Word LE_GAP_APPEARANCE_GENERIC_KEYRING = System::Word(0x240);
static const System::Word LE_GAP_APPEARANCE_GENERIC_MEDIA_PLAYER = System::Word(0x280);
static const System::Word LE_GAP_APPEARANCE_GENERIC_BARCODE_SCANNER = System::Word(0x2c0);
static const System::Word LE_GAP_APPEARANCE_GENERIC_THERMOMETER = System::Word(0x300);
static const System::Word LE_GAP_APPEARANCE_EAR_THERMOMETER = System::Word(0x301);
static const System::Word LE_GAP_APPEARANCE_GENERIC_HEART_RATE_SENSOR = System::Word(0x340);
static const System::Word LE_GAP_APPEARANCE_HEART_RATE_BELT = System::Word(0x341);
static const System::Word LE_GAP_APPEARANCE_GENERIC_BLOOD_PRESSURE = System::Word(0x380);
static const System::Word LE_GAP_APPEARANCE_ARM_BLOOD_PRESSURE = System::Word(0x381);
static const System::Word LE_GAP_APPEARANCE_WRIST_BLOOD_PRESSURE = System::Word(0x382);
static const System::Word LE_GAP_APPEARANCE_GENERIC_HUMAN_INTERFACE_DEVICE = System::Word(0x3c0);
static const System::Word LE_GAP_APPEARANCE_KEYBOARD = System::Word(0x3c1);
static const System::Word LE_GAP_APPEARANCE_MOUSE = System::Word(0x3c2);
static const System::Word LE_GAP_APPEARANCE_JOYSTICK = System::Word(0x3c3);
static const System::Word LE_GAP_APPEARANCE_GAMEPAD = System::Word(0x3c4);
static const System::Word LE_GAP_APPEARANCE_DIGITIZER_TABLET = System::Word(0x3c5);
static const System::Word LE_GAP_APPEARANCE_CARD_READER = System::Word(0x3c6);
static const System::Word LE_GAP_APPEARANCE_DIGITAL_PEN = System::Word(0x3c7);
static const System::Word LE_GAP_APPEARANCE_BARCODE_SCANNER = System::Word(0x3c8);
static const System::Word LE_GAP_APPEARANCE_TOUCHPAD = System::Word(0x3c9);
static const System::Word LE_GAP_APPEARANCE_PRESENTATION_REMOTE = System::Word(0x3ca);
static const System::Word LE_GAP_APPEARANCE_GENERIC_GLUCOSE_METER = System::Word(0x400);
static const System::Word LE_GAP_APPEARANCE_GENERIC_RUNNING_WALKING_SENSOR = System::Word(0x440);
static const System::Word LE_GAP_APPEARANCE_IN_SHOE_RUNNING_WALKING_SENSOR = System::Word(0x441);
static const System::Word LE_GAP_APPEARANCE_ON_SHOE_RUNNING_WALKING_SENSOR = System::Word(0x442);
static const System::Word LE_GAP_APPEARANCE_ON_HIP_RUNNING_WALKING_SENSOR = System::Word(0x443);
static const System::Word LE_GAP_APPEARANCE_GENERIC_CYCLING = System::Word(0x480);
static const System::Word LE_GAP_APPEARANCE_CYCLING_COMPUTER = System::Word(0x481);
static const System::Word LE_GAP_APPEARANCE_SPEED_SENSOR = System::Word(0x482);
static const System::Word LE_GAP_APPEARANCE_CADENCE_SENSOR = System::Word(0x483);
static const System::Word LE_GAP_APPEARANCE_POWER_SENSOR = System::Word(0x484);
static const System::Word LE_GAP_APPEARANCE_SPEED_AND_CADENCE_SENSOR = System::Word(0x485);
static const System::Word LE_GAP_APPEARANCE_GENERIC_CONTROL_DEVICE = System::Word(0x4c0);
static const System::Word LE_GAP_APPEARANCE_SWITCH = System::Word(0x4c1);
static const System::Word LE_GAP_APPEARANCE_MULTI_SWITCH = System::Word(0x4c2);
static const System::Word LE_GAP_APPEARANCE_BUTTON = System::Word(0x4c3);
static const System::Word LE_GAP_APPEARANCE_SLIDER = System::Word(0x4c4);
static const System::Word LE_GAP_APPEARANCE_ROTARY_SWITCH = System::Word(0x4c5);
static const System::Word LE_GAP_APPEARANCE_TOUCH_PANEL = System::Word(0x4c6);
static const System::Word LE_GAP_APPEARANCE_SINGLE_SWITCH = System::Word(0x4c7);
static const System::Word LE_GAP_APPEARANCE_DOUBLE_SWITCH = System::Word(0x4c8);
static const System::Word LE_GAP_APPEARANCE_TRIPLE_SWITCH = System::Word(0x4c9);
static const System::Word LE_GAP_APPEARANCE_BATTERY_SWITCH = System::Word(0x4ca);
static const System::Word LE_GAP_APPEARANCE_ENERGY_HARVESTING_SWITCH = System::Word(0x4cb);
static const System::Word LE_GAP_APPEARANCE_PUSH_BUTTON = System::Word(0x4cc);
static const System::Word LE_GAP_APPEARANCE_DIAL = System::Word(0x4cd);
static const System::Word LE_GAP_APPEARANCE_GENERIC_NETWORK_DEVICE = System::Word(0x500);
static const System::Word LE_GAP_APPEARANCE_ACCESS_POINT = System::Word(0x501);
static const System::Word LE_GAP_APPEARANCE_MESH_DEVICE = System::Word(0x502);
static const System::Word LE_GAP_APPEARANCE_MESH_NETWORK_PROXY = System::Word(0x503);
static const System::Word LE_GAP_APPEARANCE_GENERIC_SENSOR = System::Word(0x540);
static const System::Word LE_GAP_APPEARANCE_MOTION_SENSOR = System::Word(0x541);
static const System::Word LE_GAP_APPEARANCE_AIR_QUALITY_SENSOR = System::Word(0x542);
static const System::Word LE_GAP_APPEARANCE_TEMPERATURE_SENSOR = System::Word(0x543);
static const System::Word LE_GAP_APPEARANCE_HUMIDITY_SENSOR = System::Word(0x544);
static const System::Word LE_GAP_APPEARANCE_LEAK_SENSOR = System::Word(0x545);
static const System::Word LE_GAP_APPEARANCE_SMOKE_SENSOR = System::Word(0x546);
static const System::Word LE_GAP_APPEARANCE_OCCUPANCY_SENSOR = System::Word(0x547);
static const System::Word LE_GAP_APPEARANCE_CONTACT_SENSOR = System::Word(0x548);
static const System::Word LE_GAP_APPEARANCE_CARBON_MONOXIDE_SENSOR = System::Word(0x549);
static const System::Word LE_GAP_APPEARANCE_CARBON_DIOXIDE_SENSOR = System::Word(0x54a);
static const System::Word LE_GAP_APPEARANCE_AMBIENT_LIGHT_SENSOR = System::Word(0x54b);
static const System::Word LE_GAP_APPEARANCE_ENERGY_SENSOR = System::Word(0x54c);
static const System::Word LE_GAP_APPEARANCE_COLOR_LIGHT_SENSOR = System::Word(0x54d);
static const System::Word LE_GAP_APPEARANCE_RAIN_SENSOR = System::Word(0x54e);
static const System::Word LE_GAP_APPEARANCE_FIRE_SENSOR = System::Word(0x54f);
static const System::Word LE_GAP_APPEARANCE_WIND_SENSOR = System::Word(0x550);
static const System::Word LE_GAP_APPEARANCE_PROXIMITY_SENSOR = System::Word(0x551);
static const System::Word LE_GAP_APPEARANCE_MULTI_SENSOR = System::Word(0x552);
static const System::Word LE_GAP_APPEARANCE_FLUSH_MOUNTED_SENSOR = System::Word(0x553);
static const System::Word LE_GAP_APPEARANCE_CEILING_MOUNTED_SENSOR = System::Word(0x554);
static const System::Word LE_GAP_APPEARANCE_WALL_MOUNTED_SENSOR = System::Word(0x555);
static const System::Word LE_GAP_APPEARANCE_MULTISENSOR = System::Word(0x556);
static const System::Word LE_GAP_APPEARANCE_ENERGY_METER = System::Word(0x557);
static const System::Word LE_GAP_APPEARANCE_FLAME_DETECTOR = System::Word(0x558);
static const System::Word LE_GAP_APPEARANCE_VEHICLE_TIRE_PRESSURE_SENSOR = System::Word(0x559);
static const System::Word LE_GAP_APPEARANCE_GENERIC_LIGHT_FIXTURES = System::Word(0x580);
static const System::Word LE_GAP_APPEARANCE_WALL_LIGHT = System::Word(0x581);
static const System::Word LE_GAP_APPEARANCE_CEILING_LIGHT = System::Word(0x582);
static const System::Word LE_GAP_APPEARANCE_FLOOR_LIGHT = System::Word(0x583);
static const System::Word LE_GAP_APPEARANCE_CABINET_LIGHT = System::Word(0x584);
static const System::Word LE_GAP_APPEARANCE_DESK_LIGHT = System::Word(0x585);
static const System::Word LE_GAP_APPEARANCE_TROFFER_LIGHT = System::Word(0x586);
static const System::Word LE_GAP_APPEARANCE_PENDANT_LIGHT = System::Word(0x587);
static const System::Word LE_GAP_APPEARANCE_IN_GROUND_LIGHT = System::Word(0x588);
static const System::Word LE_GAP_APPEARANCE_FLOOD_LIGHT = System::Word(0x589);
static const System::Word LE_GAP_APPEARANCE_UNDERWATER_LIGHT = System::Word(0x58a);
static const System::Word LE_GAP_APPEARANCE_BOLLARD_WITH_LIGHT = System::Word(0x58b);
static const System::Word LE_GAP_APPEARANCE_PATHWAY_LIGHT = System::Word(0x58c);
static const System::Word LE_GAP_APPEARANCE_GARDEN_LIGHT = System::Word(0x58d);
static const System::Word LE_GAP_APPEARANCE_POLE_TOP_LIGHT = System::Word(0x58e);
static const System::Word LE_GAP_APPEARANCE_SPOTLIGHT = System::Word(0x58f);
static const System::Word LE_GAP_APPEARANCE_LINEAR_LIGHT = System::Word(0x590);
static const System::Word LE_GAP_APPEARANCE_STREET_LIGHT = System::Word(0x591);
static const System::Word LE_GAP_APPEARANCE_SHELVES_LIGHT = System::Word(0x592);
static const System::Word LE_GAP_APPEARANCE_BAY_LIGHT = System::Word(0x593);
static const System::Word LE_GAP_APPEARANCE_EMERGENCY_EXIT_LIGHT = System::Word(0x594);
static const System::Word LE_GAP_APPEARANCE_LIGHT_CONTROLLER = System::Word(0x595);
static const System::Word LE_GAP_APPEARANCE_LIGHT_DRIVER = System::Word(0x596);
static const System::Word LE_GAP_APPEARANCE_BULD = System::Word(0x597);
static const System::Word LE_GAP_APPEARANCE_LOW_BAY_LIGHT = System::Word(0x598);
static const System::Word LE_GAP_APPEARANCE_HIGH_BAY_LIGHT = System::Word(0x599);
static const System::Word LE_GAP_APPEARANCE_GENERIC_FAN = System::Word(0x5c0);
static const System::Word LE_GAP_APPEARANCE_CEILING_FAN = System::Word(0x5c1);
static const System::Word LE_GAP_APPEARANCE_AXIAL_FAN = System::Word(0x5c2);
static const System::Word LE_GAP_APPEARANCE_EXHAUST_FAN = System::Word(0x5c3);
static const System::Word LE_GAP_APPEARANCE_PEDESTAL_FAN = System::Word(0x5c4);
static const System::Word LE_GAP_APPEARANCE_DESK_FAN = System::Word(0x5c5);
static const System::Word LE_GAP_APPEARANCE_WALL_FAN = System::Word(0x5c6);
static const System::Word LE_GAP_APPEARANCE_GENERIC_HVAC = System::Word(0x600);
static const System::Word LE_GAP_APPEARANCE_THERMOSTAT = System::Word(0x601);
static const System::Word LE_GAP_APPEARANCE_HUMIDIFIER = System::Word(0x602);
static const System::Word LE_GAP_APPEARANCE_DE_HUMIDIFIER = System::Word(0x603);
static const System::Word LE_GAP_APPEARANCE_HEATER = System::Word(0x604);
static const System::Word LE_GAP_APPEARANCE_HVAC_RADIATOR = System::Word(0x605);
static const System::Word LE_GAP_APPEARANCE_HVAC_BOILER = System::Word(0x606);
static const System::Word LE_GAP_APPEARANCE_HVAC_HEAT_PUMP = System::Word(0x607);
static const System::Word LE_GAP_APPEARANCE_HVAC_INFRARED_HEATER = System::Word(0x608);
static const System::Word LE_GAP_APPEARANCE_HVAC_RADIANT_PANEL_HEATER = System::Word(0x609);
static const System::Word LE_GAP_APPEARANCE_HVAC_FAN_HEATER = System::Word(0x60a);
static const System::Word LE_GAP_APPEARANCE_HVAC_AIR_CURTAIN = System::Word(0x60b);
static const System::Word LE_GAP_APPEARANCE_GENERIC_AIR_CONDITIONING = System::Word(0x640);
static const System::Word LE_GAP_APPEARANCE_GENERIC_HUMIDIFIER = System::Word(0x680);
static const System::Word LE_GAP_APPEARANCE_GENERIC_HEATING = System::Word(0x6c0);
static const System::Word LE_GAP_APPEARANCE_RADIATOR = System::Word(0x6c1);
static const System::Word LE_GAP_APPEARANCE_BOILER = System::Word(0x6c2);
static const System::Word LE_GAP_APPEARANCE_HEAT_PUMP = System::Word(0x6c3);
static const System::Word LE_GAP_APPEARANCE_INFRARED_HEATER = System::Word(0x6c4);
static const System::Word LE_GAP_APPEARANCE_RADIANT_PANEL_HEATER = System::Word(0x6c5);
static const System::Word LE_GAP_APPEARANCE_FAN_HEATER = System::Word(0x6c6);
static const System::Word LE_GAP_APPEARANCE_AIR_CURTAIN = System::Word(0x6c7);
static const System::Word LE_GAP_APPEARANCE_GENERIC_ACCESS_CONTROL = System::Word(0x700);
static const System::Word LE_GAP_APPEARANCE_ACCESS_DOOR = System::Word(0x701);
static const System::Word LE_GAP_APPEARANCE_GARAGE_DOOR = System::Word(0x702);
static const System::Word LE_GAP_APPEARANCE_EMERGENCY_EXIT_DOOR = System::Word(0x703);
static const System::Word LE_GAP_APPEARANCE_ACCESS_LOCK = System::Word(0x704);
static const System::Word LE_GAP_APPEARANCE_ELEVATOR = System::Word(0x705);
static const System::Word LE_GAP_APPEARANCE_WINDOW = System::Word(0x706);
static const System::Word LE_GAP_APPEARANCE_ENTRANCE_GATE = System::Word(0x707);
static const System::Word LE_GAP_APPEARANCE_DOOR_LOCK = System::Word(0x708);
static const System::Word LE_GAP_APPEARANCE_LOCKER = System::Word(0x709);
static const System::Word LE_GAP_APPEARANCE_GENERIC_MOTORIZED_DEVICE = System::Word(0x740);
static const System::Word LE_GAP_APPEARANCE_MOTORIZED_GATE = System::Word(0x741);
static const System::Word LE_GAP_APPEARANCE_AWNING = System::Word(0x742);
static const System::Word LE_GAP_APPEARANCE_BLINDS_SHADES = System::Word(0x743);
static const System::Word LE_GAP_APPEARANCE_CURTAINS = System::Word(0x744);
static const System::Word LE_GAP_APPEARANCE_SCREEN = System::Word(0x745);
static const System::Word LE_GAP_APPEARANCE_GENERIC_POWER_DEVICE = System::Word(0x780);
static const System::Word LE_GAP_APPEARANCE_POWER_OUTLET = System::Word(0x781);
static const System::Word LE_GAP_APPEARANCE_POWER_STRIP = System::Word(0x782);
static const System::Word LE_GAP_APPEARANCE_PLUG = System::Word(0x783);
static const System::Word LE_GAP_APPEARANCE_POWER_SUPPLY = System::Word(0x784);
static const System::Word LE_GAP_APPEARANCE_LED_DRIVER = System::Word(0x785);
static const System::Word LE_GAP_APPEARANCE_FLUORESCENT_LAMP_GEAR = System::Word(0x786);
static const System::Word LE_GAP_APPEARANCE_HID_LAMP_GEAR = System::Word(0x787);
static const System::Word LE_GAP_APPEARANCE_CHARGE_CASE = System::Word(0x788);
static const System::Word LE_GAP_APPEARANCE_POWER_BANK = System::Word(0x789);
static const System::Word LE_GAP_APPEARANCE_GENERIC_LIGHT_SOURCE = System::Word(0x7c0);
static const System::Word LE_GAP_APPEARANCE_INCANDESCENT_LIGHT_BULB = System::Word(0x7c1);
static const System::Word LE_GAP_APPEARANCE_LED_LAMP = System::Word(0x7c2);
static const System::Word LE_GAP_APPEARANCE_HID_LAMP = System::Word(0x7c3);
static const System::Word LE_GAP_APPEARANCE_FLUORESCENT_LAMP = System::Word(0x7c4);
static const System::Word LE_GAP_APPEARANCE_LED_ARRAY = System::Word(0x7c5);
static const System::Word LE_GAP_APPEARANCE_MULTI_COLOR_LED_ARRAY = System::Word(0x7c6);
static const System::Word LE_GAP_APPEARANCE_LOW_VOLTAGE_HALOGEN = System::Word(0x7c7);
static const System::Word LE_GAP_APPEARANCE_OLED = System::Word(0x7c8);
static const System::Word LE_GAP_APPEARANCE_GEENRIC_WINDOW_COVERING = System::Word(0x800);
static const System::Word LE_GAP_APPEARANCE_WINDOW_SHADES = System::Word(0x801);
static const System::Word LE_GAP_APPEARANCE_WINDOW_BLINDS = System::Word(0x802);
static const System::Word LE_GAP_APPEARANCE_WINDOW_AWNING = System::Word(0x803);
static const System::Word LE_GAP_APPEARANCE_WINDOW_CURTAIN = System::Word(0x804);
static const System::Word LE_GAP_APPEARANCE_EXTERIOR_SHUTTER = System::Word(0x805);
static const System::Word LE_GAP_APPEARANCE_EXTERIOR_SCREEN = System::Word(0x806);
static const System::Word LE_GAP_APPEARANCE_GENERIC_AUDIO_SINK = System::Word(0x840);
static const System::Word LE_GAP_APPEARANCE_STANDALONE_SPEAKER = System::Word(0x841);
static const System::Word LE_GAP_APPEARANCE_SOUNDBAR = System::Word(0x842);
static const System::Word LE_GAP_APPEARANCE_BOOKSHELF_SPEAKER = System::Word(0x843);
static const System::Word LE_GAP_APPEARANCE_STANDMOUNTED_SPEAKER = System::Word(0x844);
static const System::Word LE_GAP_APPEARANCE_SPEAKERPHONE = System::Word(0x845);
static const System::Word LE_GAP_APPEARANCE_GENERIC_AUDIO_SOURCE = System::Word(0x880);
static const System::Word LE_GAP_APPEARANCE_MICROPHONE = System::Word(0x881);
static const System::Word LE_GAP_APPEARANCE_ALARM = System::Word(0x882);
static const System::Word LE_GAP_APPEARANCE_BELL = System::Word(0x883);
static const System::Word LE_GAP_APPEARANCE_HORN = System::Word(0x884);
static const System::Word LE_GAP_APPEARANCE_BROADCASTING_DEVICE = System::Word(0x885);
static const System::Word LE_GAP_APPEARANCE_SERVICE_DESK = System::Word(0x886);
static const System::Word LE_GAP_APPEARANCE_KIOSK = System::Word(0x887);
static const System::Word LE_GAP_APPEARANCE_BROADCASTING_ROOM = System::Word(0x888);
static const System::Word LE_GAP_APPEARANCE_AUDITORIUM = System::Word(0x889);
static const System::Word LE_GAP_APPEARANCE_GENERIC_MOTORIZED_VEHICLE = System::Word(0x8c0);
static const System::Word LE_GAP_APPEARANCE_CAR = System::Word(0x8c1);
static const System::Word LE_GAP_APPEARANCE_LARGE_GOODS_VEHICLE = System::Word(0x8c2);
static const System::Word LE_GAP_APPEARANCE_2_WHEELED_VEHICLE = System::Word(0x8c3);
static const System::Word LE_GAP_APPEARANCE_MOTORBIKE = System::Word(0x8c4);
static const System::Word LE_GAP_APPEARANCE_SCOOTER = System::Word(0x8c5);
static const System::Word LE_GAP_APPEARANCE_MOPED = System::Word(0x8c6);
static const System::Word LE_GAP_APPEARANCE_3_WHEELED_VEHICLE = System::Word(0x8c7);
static const System::Word LE_GAP_APPEARANCE_LIGHT_VEHICLE = System::Word(0x8c8);
static const System::Word LE_GAP_APPEARANCE_QUAD_BIKE = System::Word(0x8c9);
static const System::Word LE_GAP_APPEARANCE_MINIBUS = System::Word(0x8ca);
static const System::Word LE_GAP_APPEARANCE_BUS = System::Word(0x8cb);
static const System::Word LE_GAP_APPEARANCE_TROLLEY = System::Word(0x8cc);
static const System::Word LE_GAP_APPEARANCE_AGRICULTURAL_VEHICLE = System::Word(0x8cd);
static const System::Word LE_GAP_APPEARANCE_CAMPER = System::Word(0x8ce);
static const System::Word LE_GAP_APPEARANCE_RECREATIONAL_VEHICLE = System::Word(0x8cf);
static const System::Word LE_GAP_APPEARANCE_GENERIC_DOMESTIC_APPLIANCE = System::Word(0x900);
static const System::Word LE_GAP_APPEARANCE_REFRIGERATOR = System::Word(0x901);
static const System::Word LE_GAP_APPEARANCE_FREEZER = System::Word(0x902);
static const System::Word LE_GAP_APPEARANCE_OVEN = System::Word(0x903);
static const System::Word LE_GAP_APPEARANCE_MICROWAVE = System::Word(0x904);
static const System::Word LE_GAP_APPEARANCE_TOASTER = System::Word(0x905);
static const System::Word LE_GAP_APPEARANCE_WASHING_MACHINE = System::Word(0x906);
static const System::Word LE_GAP_APPEARANCE_DRYER = System::Word(0x907);
static const System::Word LE_GAP_APPEARANCE_COFFEE_MAKER = System::Word(0x908);
static const System::Word LE_GAP_APPEARANCE_CLOTHES_IRON = System::Word(0x909);
static const System::Word LE_GAP_APPEARANCE_CURLING_IRON = System::Word(0x90a);
static const System::Word LE_GAP_APPEARANCE_HAIR_DRYER = System::Word(0x90b);
static const System::Word LE_GAP_APPEARANCE_VACUUM_CLEANER = System::Word(0x90c);
static const System::Word LE_GAP_APPEARANCE_ROBOTIC_VACUUM_CLEANER = System::Word(0x90d);
static const System::Word LE_GAP_APPEARANCE_RICE_COOKER = System::Word(0x90e);
static const System::Word LE_GAP_APPEARANCE_CLOTHES_STEAMER = System::Word(0x90f);
static const System::Word LE_GAP_APPEARANCE_GENERIC_WARABLE_AUDIO_DEVICE = System::Word(0x940);
static const System::Word LE_GAP_APPEARANCE_EARBUD = System::Word(0x941);
static const System::Word LE_GAP_APPEARANCE_HEADSET = System::Word(0x942);
static const System::Word LE_GAP_APPEARANCE_HEADPHONES = System::Word(0x943);
static const System::Word LE_GAP_APPEARANCE_NECK_BAND = System::Word(0x944);
static const System::Word LE_GAP_APPEARANCE_GENERIC_AIRCRAFT = System::Word(0x980);
static const System::Word LE_GAP_APPEARANCE_LIGHT_AIRCRAFT = System::Word(0x981);
static const System::Word LE_GAP_APPEARANCE_MICROLIGHT = System::Word(0x982);
static const System::Word LE_GAP_APPEARANCE_PARAGLIDER = System::Word(0x983);
static const System::Word LE_GAP_APPEARANCE_LARGE_PASSENGER_AIRCRAFT = System::Word(0x984);
static const System::Word LE_GAP_APPEARANCE_GENERIC_AV_EQUIPMENT = System::Word(0x9c0);
static const System::Word LE_GAP_APPEARANCE_AMPLIFIER = System::Word(0x9c1);
static const System::Word LE_GAP_APPEARANCE_RECEIVER = System::Word(0x9c2);
static const System::Word LE_GAP_APPEARANCE_RADIO = System::Word(0x9c3);
static const System::Word LE_GAP_APPEARANCE_TUNER = System::Word(0x9c4);
static const System::Word LE_GAP_APPEARANCE_TURNTABLE = System::Word(0x9c5);
static const System::Word LE_GAP_APPEARANCE_CD_PLAYER = System::Word(0x9c6);
static const System::Word LE_GAP_APPEARANCE_DVD_PLAYER = System::Word(0x9c7);
static const System::Word LE_GAP_APPEARANCE_BLURAY_PLAYER = System::Word(0x9c8);
static const System::Word LE_GAP_APPEARANCE_OPTICAL_DISC_PLAYER = System::Word(0x9c9);
static const System::Word LE_GAP_APPEARANCE_SET_TOP_BOX = System::Word(0x9ca);
static const System::Word LE_GAP_APPEARANCE_GENERIC_DISPLAY_EQUIPMENT = System::Word(0xa00);
static const System::Word LE_GAP_APPEARANCE_TELEVISION = System::Word(0xa01);
static const System::Word LE_GAP_APPEARANCE_MONITOR = System::Word(0xa02);
static const System::Word LE_GAP_APPEARANCE_PROJECTOR = System::Word(0xa03);
static const System::Word LE_GAP_APPEARANCE_GENERIC_HEARING_AID = System::Word(0xa40);
static const System::Word LE_GAP_APPEARANCE_IN_EAR_HEARING_AID = System::Word(0xa41);
static const System::Word LE_GAP_APPEARANCE_BEHIND_EAR_HEARING_AID = System::Word(0xa42);
static const System::Word LE_GAP_APPEARANCE_COCHLEAR_IMPLANT = System::Word(0xa43);
static const System::Word LE_GAP_APPEARANCE_GENERIC_GAMING = System::Word(0xa80);
static const System::Word LE_GAP_APPEARANCE_HOME_VIDEO_GAME_CONSOLE = System::Word(0xa81);
static const System::Word LE_GAP_APPEARANCE_PORTABLE_HANDHELD_CONSOLE = System::Word(0xa82);
static const System::Word LE_GAP_APPEARANCE_GENERIC_SIGNAGE = System::Word(0xac0);
static const System::Word LE_GAP_APPEARANCE_DIGITAL_SIGNAGE = System::Word(0xac1);
static const System::Word LE_GAP_APPEARANCE_ELECTRONIC_LABEL = System::Word(0xac2);
static const System::Word LE_GAP_APPEARANCE_GENERIC_PULSE_OXIMETER = System::Word(0xc40);
static const System::Word LE_GAP_APPEARANCE_FINGERTIP_PULSE_OXIMETER = System::Word(0xc41);
static const System::Word LE_GAP_APPEARANCE_WRIST_WORN_PULSE_OXIMETER = System::Word(0xc42);
static const System::Word LE_GAP_APPEARANCE_GENERIC_WEIGHT_SCALE = System::Word(0xc80);
static const System::Word LE_GAP_APPEARANCE_GENERIC_PERSONAL_MOBILITY_DEVICE = System::Word(0xcc0);
static const System::Word LE_GAP_APPEARANCE_POWERED_WHEELCHAIR = System::Word(0xcc1);
static const System::Word LE_GAP_APPEARANCE_MOBILITY_SCOOTER = System::Word(0xcc2);
static const System::Word LE_GAP_APPEARANCE_GENERIC_CONTINUOUS_GLUCOSE_MONITOR = System::Word(0xd00);
static const System::Word LE_GAP_APPEARANCE_GENERIC_INSULIN_PUMP = System::Word(0xd40);
static const System::Word LE_GAP_APPEARANCE_INSULIN_PUMP_DURABLE = System::Word(0xd41);
static const System::Word LE_GAP_APPEARANCE_INSULIN_PUMP_PATCH = System::Word(0xd44);
static const System::Word LE_GAP_APPEARANCE_INSULIN_PEN = System::Word(0xd48);
static const System::Word LE_GAP_APPEARANCE_GENERIC_MEDICATION_DELIVERY = System::Word(0xd80);
static const System::Word LE_GAP_APPEARANCE_GENERIC_SPIROMETER = System::Word(0xdc0);
static const System::Word LE_GAP_APPEARANCE_HANDHELD_SPIROMETER = System::Word(0xdc1);
static const System::Word LE_GAP_APPEARANCE_GENERIC_OUTDOOR_SPORTS_ACTIVITY = System::Word(0x1440);
static const System::Word LE_GAP_APPEARANCE_LOCATION_DISPLAY = System::Word(0x1441);
static const System::Word LE_GAP_APPEARANCE_LOCATION_NAVIGATION_DISPLAY = System::Word(0x1442);
static const System::Word LE_GAP_APPEARANCE_LOCATION_POD = System::Word(0x1443);
static const System::Word LE_GAP_APPEARANCE_LOCATION_NAVIGATION_POD = System::Word(0x1444);
static const System::Int8 LE_GAP_AD_TYPE_NONE = System::Int8(0x0);
static const System::Int8 LE_GAP_AD_TYPE_FLAGS = System::Int8(0x1);
static const System::Int8 LE_GAP_AD_TYPE_SERVICES_16_MORE = System::Int8(0x2);
static const System::Int8 LE_GAP_AD_TYPE_SERVICES_16_ALL = System::Int8(0x3);
static const System::Int8 LE_GAP_AD_TYPE_SERVICES_32_MORE = System::Int8(0x4);
static const System::Int8 LE_GAP_AD_TYPE_SERVICES_32_ALL = System::Int8(0x5);
static const System::Int8 LE_GAP_AD_TYPE_SERVICES_128_MORE = System::Int8(0x6);
static const System::Int8 LE_GAP_AD_TYPE_SERVICES_128_ALL = System::Int8(0x7);
static const System::Int8 LE_GAP_AD_TYPE_LOCAL_NAME_SHORT = System::Int8(0x8);
static const System::Int8 LE_GAP_AD_TYPE_LOCAL_NAME_COMPLETE = System::Int8(0x9);
static const System::Int8 LE_GAP_AD_TYPE_TXPOWER = System::Int8(0xa);
static const System::Int8 LE_GAP_AD_TYPE_COD = System::Int8(0xd);
static const System::Int8 LE_GAP_AD_TYPE_PAIRING_HASH_C = System::Int8(0xe);
static const System::Int8 LE_GAP_AD_TYPE_PAIRING_RAND_R = System::Int8(0xf);
static const System::Int8 LE_GAP_AD_TYPE_DEVICE_ID = System::Int8(0x10);
static const System::Int8 LE_GAP_AD_TYPE_SM_OOB_FLAGS = System::Int8(0x11);
static const System::Int8 LE_GAP_AD_TYPE_CON_INTERVALS = System::Int8(0x12);
static const System::Int8 LE_GAP_AD_TYPE_SERVICE_SOL_UUIDS_16 = System::Int8(0x14);
static const System::Int8 LE_GAP_AD_TYPE_SERVICE_SOL_UUIDS_128 = System::Int8(0x15);
static const System::Int8 LE_GAP_AD_TYPE_SERVICE_DATA_16 = System::Int8(0x16);
static const System::Int8 LE_GAP_AD_TYPE_PUBLIC_TARGET_ADDRESS = System::Int8(0x17);
static const System::Int8 LE_GAP_AD_TYPE_RANDOM_TARGET_ADDRESS = System::Int8(0x18);
static const System::Int8 LE_GAP_AD_TYPE_APPEARANCE = System::Int8(0x19);
static const System::Int8 LE_GAP_AD_TYPE_ADV_INTERVAL = System::Int8(0x1a);
static const System::Int8 LE_GAP_AD_TYPE_ADDRESS = System::Int8(0x1b);
static const System::Int8 LE_GAP_AD_TYPE_ROLE = System::Int8(0x1c);
static const System::Int8 LE_GAP_AD_TYPE_PAIRING_HASH_C_256 = System::Int8(0x1d);
static const System::Int8 LE_GAP_AD_TYPE_PAIRING_RAND_R_256 = System::Int8(0x1e);
static const System::Int8 LE_GAP_AD_TYPE_SERVICE_SOL_UUIDS_32 = System::Int8(0x1f);
static const System::Int8 LE_GAP_AD_TYPE_SERVICE_DATA_32 = System::Int8(0x20);
static const System::Int8 LE_GAP_AD_TYPE_SERVICE_DATA_128 = System::Int8(0x21);
static const System::Int8 LE_GAP_AD_TYPE_SECURE_CONFIRM = System::Int8(0x22);
static const System::Int8 LE_GAP_AD_TYPE_SECURE_RAND = System::Int8(0x23);
static const System::Int8 LE_GAP_AD_TYPE_URI = System::Int8(0x24);
static const System::Int8 LE_GAP_AD_TYPE_INDOOR_POS = System::Int8(0x25);
static const System::Int8 LE_GAP_AD_TYPE_TRANS_DISC_DATA = System::Int8(0x26);
static const System::Int8 LE_GAP_AD_TYPE_FEATURES = System::Int8(0x27);
static const System::Int8 LE_GAP_AD_TYPE_CH_MAP = System::Int8(0x28);
static const System::Int8 LE_GAP_AD_TYPE_PB_ADV = System::Int8(0x29);
static const System::Int8 LE_GAP_AD_TYPE_MESH_MSG = System::Int8(0x2a);
static const System::Int8 LE_GAP_AD_TYPE_MESH_BEACON = System::Int8(0x2b);
static const System::Int8 LE_GAP_AD_TYPE_BIG_INGO = System::Int8(0x2c);
static const System::Int8 LE_GAP_AD_TYPE_BROADCAST_CODE = System::Int8(0x2d);
static const System::Int8 LE_GAP_AD_TYPE_3D_INFO = System::Int8(0x3d);
static const System::Byte LE_GAP_AD_TYPE_MANUFACTURER = System::Byte(0xff);
static const System::Word EDDYSTONE_BEACON_UUID_16 = System::Word(0xfeaa);
static const System::Int8 EDDYSTONE_UID_FRAME_ID = System::Int8(0x0);
static const System::Int8 EDDYSTONE_URL_FRAME_ID = System::Int8(0x10);
static const System::Int8 EDDYSTONE_TLM_FRAME_ID = System::Int8(0x20);
static const System::Word DRI_ASD_UUID_16 = System::Word(0xfffa);
}	/* namespace Wcluuids */
#if !defined(DELPHIHEADER_NO_IMPLICIT_NAMESPACE_USE) && !defined(NO_USING_NAMESPACE_WCLUUIDS)
using namespace Wcluuids;
#endif
#pragma pack(pop)
#pragma option pop

#pragma delphiheader end.
//-- end unit ----------------------------------------------------------------
#endif	// WcluuidsHPP
